//
// This source file belongs to the My Heart Counts Android project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT

// Generated by Scripts/generate-grove-fhir-kotlin-contract.py. Do not edit by hand.

package org.grovealliance.health.fhir

/** Canonicals shared with the Grove FHIR Mobile and Health Connect packages. */
object HealthConnectContract {
    const val FHIR_VERSION = "4.0.1"
    const val PACKAGE_VERSION = "0.5.0"
    const val CONVERSION_CONTRACT_VERSION = "health-connect-r4-0.5.0"
    const val CANONICAL_ROOT = "https://grovealliance.org/fhir"
    const val MOBILE_BASE = "$CANONICAL_ROOT/mobile"
    const val HEALTH_CONNECT_BASE = "$CANONICAL_ROOT/health-connect"

    const val MOBILE_OBSERVATION_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-observation"
    const val MOBILE_EXCHANGE_BUNDLE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-exchange-bundle"
    const val MOBILE_APPLICATION_DEVICE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-application-device"
    const val MOBILE_RECORDING_DEVICE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-recording-device"
    const val HEALTH_CONNECT_OBSERVATION_PROFILE = "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-observation"
    const val HEALTH_CONNECT_SPECIMEN_PROFILE = "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-specimen"
    const val HEALTH_CONNECT_PROVENANCE_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-conversion-provenance"

    const val MOBILE_ACTIVE_ENERGY_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-active-energy"
    const val MOBILE_BASAL_BODY_TEMPERATURE_PROFILE =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-basal-body-temperature"
    const val MOBILE_BLOOD_PRESSURE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-blood-pressure"
    const val MOBILE_BODY_FAT_PERCENTAGE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-body-fat-percentage"
    const val MOBILE_BODY_HEIGHT_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-body-height"
    const val MOBILE_BODY_TEMPERATURE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-body-temperature"
    const val MOBILE_BODY_WATER_MASS_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-body-water-mass"
    const val MOBILE_BODY_WEIGHT_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-body-weight"
    const val MOBILE_BONE_MASS_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-bone-mass"
    const val MOBILE_CERVICAL_MUCUS_QUALITY_PROFILE =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-cervical-mucus-quality"
    const val MOBILE_CYCLING_CADENCE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-cycling-cadence"
    const val MOBILE_DISTANCE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-distance"
    const val MOBILE_FLIGHTS_CLIMBED_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-flights-climbed"
    const val MOBILE_FLUID_INTAKE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-fluid-intake"
    const val MOBILE_HEART_RATE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-heart-rate"
    const val MOBILE_HEART_RATE_VARIABILITY_RMSSD_PROFILE =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-heart-rate-variability-rmssd"
    const val MOBILE_INTERMENSTRUAL_BLEEDING_PROFILE =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-intermenstrual-bleeding"
    const val MOBILE_LEAN_BODY_MASS_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-lean-body-mass"
    const val MOBILE_MENSTRUATION_FLOW_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-menstruation-flow"
    const val MOBILE_MINDFULNESS_SESSION_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-mindfulness-session"
    const val MOBILE_OVULATION_TEST_RESULT_PROFILE =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-ovulation-test-result"
    const val MOBILE_OXYGEN_SATURATION_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-oxygen-saturation"
    const val MOBILE_POWER_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-power"
    const val MOBILE_RESPIRATORY_RATE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-respiratory-rate"
    const val MOBILE_RESTING_HEART_RATE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-resting-heart-rate"
    const val MOBILE_SEXUAL_ACTIVITY_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-sexual-activity"
    const val MOBILE_SKIN_TEMPERATURE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-skin-temperature"
    const val MOBILE_SLEEP_DURATION_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-sleep-duration"
    const val MOBILE_SLEEP_STAGE_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-sleep-stage"
    const val MOBILE_SPEED_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-speed"
    const val MOBILE_STEP_COUNT_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-step-count"
    const val MOBILE_VO2_MAX_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-vo2-max"
    const val MOBILE_WHEELCHAIR_PUSH_COUNT_PROFILE =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-wheelchair-push-count"
    const val MOBILE_WORKOUT_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-workout"
    const val MOBILE_WORKOUT_SEGMENT_PROFILE = "$MOBILE_BASE/StructureDefinition/grove-mobile-workout-segment"

    const val HEALTH_CONNECT_BASAL_METABOLIC_RATE_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-basal-metabolic-rate"
    const val HEALTH_CONNECT_WHOLE_BLOOD_GLUCOSE_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-whole-blood-glucose"
    const val HEALTH_CONNECT_CAPILLARY_BLOOD_GLUCOSE_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-capillary-blood-glucose"
    const val HEALTH_CONNECT_DIETARY_ENERGY_FROM_FAT_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-dietary-energy-from-fat"
    const val HEALTH_CONNECT_DIETARY_FAT_TRANS_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-dietary-fat-trans"
    const val HEALTH_CONNECT_DIETARY_FAT_UNSATURATED_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-dietary-fat-unsaturated"
    const val HEALTH_CONNECT_DIETARY_FOLIC_ACID_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-dietary-folic-acid"
    const val HEALTH_CONNECT_ELEVATION_GAINED_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-elevation-gained"
    const val HEALTH_CONNECT_INTERSTITIAL_GLUCOSE_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-interstitial-glucose"
    const val HEALTH_CONNECT_MENSTRUATION_PERIOD_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-menstruation-period"
    const val HEALTH_CONNECT_SERUM_PLASMA_GLUCOSE_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-serum-plasma-glucose"
    const val HEALTH_CONNECT_STEP_CADENCE_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-step-cadence"
    const val HEALTH_CONNECT_TOTAL_ENERGY_PROFILE =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-total-energy"

    /** Every dietary nutrient the adapter emits, keyed by its catalog measurement id. */
    val mobileDietaryProfiles: Map<String, String> = mapOf(
        "dietary-biotin" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-biotin",
        "dietary-caffeine" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-caffeine",
        "dietary-calcium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-calcium",
        "dietary-carbohydrates" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-carbohydrates",
        "dietary-chloride" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-chloride",
        "dietary-cholesterol" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-cholesterol",
        "dietary-chromium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-chromium",
        "dietary-copper" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-copper",
        "dietary-energy" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-energy",
        "dietary-fat-monounsaturated" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-fat-monounsaturated",
        "dietary-fat-polyunsaturated" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-fat-polyunsaturated",
        "dietary-fat-saturated" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-fat-saturated",
        "dietary-fat-total" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-fat-total",
        "dietary-fiber" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-fiber",
        "dietary-folate" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-folate",
        "dietary-iodine" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-iodine",
        "dietary-iron" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-iron",
        "dietary-magnesium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-magnesium",
        "dietary-manganese" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-manganese",
        "dietary-molybdenum" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-molybdenum",
        "dietary-niacin" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-niacin",
        "dietary-pantothenic-acid" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-pantothenic-acid",
        "dietary-phosphorus" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-phosphorus",
        "dietary-potassium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-potassium",
        "dietary-protein" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-protein",
        "dietary-riboflavin" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-riboflavin",
        "dietary-selenium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-selenium",
        "dietary-sodium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-sodium",
        "dietary-sugar" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-sugar",
        "dietary-thiamin" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-thiamin",
        "dietary-vitamin-a" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-a",
        "dietary-vitamin-b12" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-b12",
        "dietary-vitamin-b6" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-b6",
        "dietary-vitamin-c" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-c",
        "dietary-vitamin-d" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-d",
        "dietary-vitamin-e" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-e",
        "dietary-vitamin-k" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-k",
        "dietary-zinc" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-zinc",
    )

    /** Profiles the shared Mobile package owns, which this adapter also claims. */
    val sharedMeasurementProfiles: Set<String> = setOf(
        MOBILE_ACTIVE_ENERGY_PROFILE,
        MOBILE_BASAL_BODY_TEMPERATURE_PROFILE,
        MOBILE_BLOOD_PRESSURE_PROFILE,
        MOBILE_BODY_FAT_PERCENTAGE_PROFILE,
        MOBILE_BODY_HEIGHT_PROFILE,
        MOBILE_BODY_TEMPERATURE_PROFILE,
        MOBILE_BODY_WATER_MASS_PROFILE,
        MOBILE_BODY_WEIGHT_PROFILE,
        MOBILE_BONE_MASS_PROFILE,
        MOBILE_CERVICAL_MUCUS_QUALITY_PROFILE,
        MOBILE_CYCLING_CADENCE_PROFILE,
        MOBILE_DISTANCE_PROFILE,
        MOBILE_FLIGHTS_CLIMBED_PROFILE,
        MOBILE_FLUID_INTAKE_PROFILE,
        MOBILE_HEART_RATE_PROFILE,
        MOBILE_HEART_RATE_VARIABILITY_RMSSD_PROFILE,
        MOBILE_INTERMENSTRUAL_BLEEDING_PROFILE,
        MOBILE_LEAN_BODY_MASS_PROFILE,
        MOBILE_MENSTRUATION_FLOW_PROFILE,
        MOBILE_MINDFULNESS_SESSION_PROFILE,
        MOBILE_OVULATION_TEST_RESULT_PROFILE,
        MOBILE_OXYGEN_SATURATION_PROFILE,
        MOBILE_POWER_PROFILE,
        MOBILE_RESPIRATORY_RATE_PROFILE,
        MOBILE_RESTING_HEART_RATE_PROFILE,
        MOBILE_SEXUAL_ACTIVITY_PROFILE,
        MOBILE_SKIN_TEMPERATURE_PROFILE,
        MOBILE_SLEEP_DURATION_PROFILE,
        MOBILE_SLEEP_STAGE_PROFILE,
        MOBILE_SPEED_PROFILE,
        MOBILE_STEP_COUNT_PROFILE,
        MOBILE_VO2_MAX_PROFILE,
        MOBILE_WHEELCHAIR_PUSH_COUNT_PROFILE,
        MOBILE_WORKOUT_PROFILE,
        MOBILE_WORKOUT_SEGMENT_PROFILE,
    ) + mobileDietaryProfiles.values

    /** Profiles only this adapter publishes. */
    val adapterSpecificObservationProfiles: Set<String> = setOf(
        HEALTH_CONNECT_BASAL_METABOLIC_RATE_PROFILE,
        HEALTH_CONNECT_WHOLE_BLOOD_GLUCOSE_PROFILE,
        HEALTH_CONNECT_CAPILLARY_BLOOD_GLUCOSE_PROFILE,
        HEALTH_CONNECT_DIETARY_ENERGY_FROM_FAT_PROFILE,
        HEALTH_CONNECT_DIETARY_FAT_TRANS_PROFILE,
        HEALTH_CONNECT_DIETARY_FAT_UNSATURATED_PROFILE,
        HEALTH_CONNECT_DIETARY_FOLIC_ACID_PROFILE,
        HEALTH_CONNECT_ELEVATION_GAINED_PROFILE,
        HEALTH_CONNECT_INTERSTITIAL_GLUCOSE_PROFILE,
        HEALTH_CONNECT_MENSTRUATION_PERIOD_PROFILE,
        HEALTH_CONNECT_SERUM_PLASMA_GLUCOSE_PROFILE,
        HEALTH_CONNECT_STEP_CADENCE_PROFILE,
        HEALTH_CONNECT_TOTAL_ENERGY_PROFILE,
    )

    const val HEALTH_CONNECT_RECORD_IDENTIFIER = "$HEALTH_CONNECT_BASE/NamingSystem/health-connect-record-id"
    const val HEALTH_CONNECT_OUTPUT_IDENTIFIER = "$HEALTH_CONNECT_BASE/NamingSystem/health-connect-output-id"
    const val HEALTH_CONNECT_SPECIMEN_IDENTIFIER = "$HEALTH_CONNECT_BASE/NamingSystem/health-connect-specimen-id"
    const val ANDROID_PACKAGE_IDENTIFIER = "$HEALTH_CONNECT_BASE/NamingSystem/android-package-name"

    const val WRITER_RECORD_IDENTIFIER = "$MOBILE_BASE/NamingSystem/grove-writer-record-id"
    const val WRITER_RECORD_VERSION = "$MOBILE_BASE/StructureDefinition/grove-writer-record-version"
    const val RECORDING_METHOD_EXTENSION = "$MOBILE_BASE/StructureDefinition/grove-recording-method"
    const val HEALTH_CONNECT_SLEEP_TITLE = "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-sleep-title"
    const val HEALTH_CONNECT_EXERCISE_TITLE = "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-exercise-title"
    const val HEALTH_CONNECT_GLUCOSE_MEAL_CONTEXT =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-glucose-meal-context"
    const val HEALTH_CONNECT_RECORD_TYPE_EXTENSION =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-record-type"

    const val GROVE_AGGREGATION_METHOD = "$MOBILE_BASE/CodeSystem/grove-aggregation-method"
    const val GROVE_APPLICATION_VERSION_TYPE = "$MOBILE_BASE/CodeSystem/grove-application-version-type"
    const val GROVE_CERVICAL_MUCUS_QUALITY = "$MOBILE_BASE/CodeSystem/grove-cervical-mucus-quality"
    const val GROVE_CERVICAL_MUCUS_SENSATION = "$MOBILE_BASE/CodeSystem/grove-cervical-mucus-sensation"
    const val GROVE_INTERMENSTRUAL_BLEEDING = "$MOBILE_BASE/CodeSystem/grove-intermenstrual-bleeding"
    const val GROVE_MENSTRUAL_CYCLE_START = "$MOBILE_BASE/CodeSystem/grove-menstrual-cycle-start"
    const val GROVE_MENSTRUATION_FLOW = "$MOBILE_BASE/CodeSystem/grove-menstruation-flow"
    const val GROVE_MOBILE_MEASUREMENT = "$MOBILE_BASE/CodeSystem/grove-mobile-measurement"
    const val GROVE_OVULATION_TEST_RESULT = "$MOBILE_BASE/CodeSystem/grove-ovulation-test-result"
    const val GROVE_RECORDING_METHOD = "$MOBILE_BASE/CodeSystem/grove-recording-method"
    const val GROVE_SEXUAL_ACTIVITY = "$MOBILE_BASE/CodeSystem/grove-sexual-activity"
    const val GROVE_SLEEP_STAGE = "$MOBILE_BASE/CodeSystem/grove-sleep-stage"
    const val GROVE_WORKOUT_ACTIVITY = "$MOBILE_BASE/CodeSystem/grove-workout-activity"
    const val GROVE_WORKOUT_SEGMENT_TYPE = "$MOBILE_BASE/CodeSystem/grove-workout-segment-type"
    const val GROVE_WORKOUT_STATISTIC = "$MOBILE_BASE/CodeSystem/grove-workout-statistic"
    const val HEALTH_CONNECT_CERVICAL_MUCUS_APPEARANCE =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-cervical-mucus-appearance"
    const val HEALTH_CONNECT_CERVICAL_MUCUS_SENSATION =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-cervical-mucus-sensation"
    const val HEALTH_CONNECT_CONCEPT_PROPERTY = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-concept-property"
    const val HEALTH_CONNECT_EXERCISE_SEGMENT_TYPE =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-exercise-segment-type"
    const val HEALTH_CONNECT_EXERCISE_TYPE = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-exercise-type"
    const val HEALTH_CONNECT_MEAL_TYPE = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-meal-type"
    const val HEALTH_CONNECT_MEASUREMENT = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-measurement"
    const val HEALTH_CONNECT_MENSTRUATION_FLOW = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-menstruation-flow"
    const val HEALTH_CONNECT_MENSTRUATION_PERIOD = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-menstruation-period"
    const val HEALTH_CONNECT_OVULATION_TEST_RESULT =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-ovulation-test-result"
    const val HEALTH_CONNECT_RECORD_TYPE = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-record-type"
    const val HEALTH_CONNECT_RELATION_TO_MEAL = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-relation-to-meal"
    const val HEALTH_CONNECT_SEXUAL_ACTIVITY_PROTECTION =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-sexual-activity-protection"
    const val HEALTH_CONNECT_SLEEP_STAGE = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-sleep-stage"

    const val OBSERVATION_BODY_POSITION = "http://hl7.org/fhir/StructureDefinition/observation-bodyPosition"
    const val LOINC = "http://loinc.org"
    const val SNOMED_CT = "http://snomed.info/sct"
    const val UCUM = "http://unitsofmeasure.org"
    const val MDC = "urn:iso:std:iso:11073:10101"

    /** The ISO 11073 MDC software-revision code. */
    const val APPLICATION_SOFTWARE_VERSION = "531975"
    const val OBSERVATION_CATEGORY = "http://terminology.hl7.org/CodeSystem/observation-category"
    const val RECORD_LIFECYCLE = "http://terminology.hl7.org/CodeSystem/iso-21089-lifecycle"
    const val PROVENANCE_PARTICIPANT = "http://terminology.hl7.org/CodeSystem/provenance-participant-type"
    const val RESEARCH_STUDY_EXTENSION = "http://hl7.org/fhir/StructureDefinition/workflow-researchStudy"
}
