//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT

// Generated by Scripts/generate-grove-fhir-kotlin-contract.py. Do not edit by hand.

package org.grovealliance.health.fhir

/** Every Health Connect context mapping, keyed by the exact AndroidX source token. */
internal object HealthConnectContextMappings {
    val sleepStage: SourceCodedMapping = HEALTH_CONNECT_SLEEP_STAGE

    val menstruationFlow: SourceCodedMapping = HEALTH_CONNECT_MENSTRUATION_FLOW

    val ovulationTestResult: SourceCodedMapping = HEALTH_CONNECT_OVULATION_TEST_RESULT

    val sexualActivityProtection: SourceCodedMapping = HEALTH_CONNECT_SEXUAL_ACTIVITY_PROTECTION

    val cervicalMucusAppearance: SourceCodedMapping = HEALTH_CONNECT_CERVICAL_MUCUS_APPEARANCE

    val cervicalMucusSensation: SourceCodedMapping = HEALTH_CONNECT_CERVICAL_MUCUS_SENSATION

    val mindfulnessSessionType: SourceOnlyMapping = HEALTH_CONNECT_MINDFULNESS_SESSION_TYPE

    val vo2MaxMeasurementMethod: SourceOnlyMapping = HEALTH_CONNECT_VO2_MAX_MEASUREMENT_METHOD

    val relationToMeal: SourceOnlyMapping = HEALTH_CONNECT_RELATION_TO_MEAL

    val mealType: SourceOnlyMapping = HEALTH_CONNECT_MEAL_TYPE

    val bloodPressureBodyPosition: ExternalCodedMapping = HEALTH_CONNECT_BLOOD_PRESSURE_BODY_POSITION

    val bloodPressureMeasurementLocation: ExternalCodedMapping = HEALTH_CONNECT_BLOOD_PRESSURE_MEASUREMENT_LOCATION

    val temperatureMeasurementLocation: ExternalCodedMapping = HEALTH_CONNECT_TEMPERATURE_MEASUREMENT_LOCATION

    val skinTemperatureMeasurementLocation: ExternalCodedMapping = HEALTH_CONNECT_SKIN_TEMPERATURE_MEASUREMENT_LOCATION

    val bloodGlucoseSpecimen: List<SpecimenSourceValue> = HEALTH_CONNECT_BLOOD_GLUCOSE_SPECIMEN

    val exerciseType: AllowedSourceCodes = HEALTH_CONNECT_EXERCISE_TYPE

    val exerciseSegmentType: AllowedSourceCodes = HEALTH_CONNECT_EXERCISE_SEGMENT_TYPE

    /** Display strings of every Grove CodeSystem concept, by system and code. */
    val displays: Map<String, Map<String, String>> = CONCEPT_DISPLAYS
}

private val HEALTH_CONNECT_SLEEP_STAGE: SourceCodedMapping = SourceCodedMapping(
    sourceSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-sleep-stage",
    appliesToMeasurement = "sleep-stage",
    values = listOf(
        SourceCodedValue(
            source = "STAGE_TYPE_UNKNOWN",
            code = "STAGE_TYPE_UNKNOWN",
            display = "Unknown",
            shared = "unknown",
        ),
        SourceCodedValue(
            source = "STAGE_TYPE_AWAKE",
            code = "STAGE_TYPE_AWAKE",
            display = "Awake",
            shared = "awake",
        ),
        SourceCodedValue(
            source = "STAGE_TYPE_SLEEPING",
            code = "STAGE_TYPE_SLEEPING",
            display = "Sleeping",
            shared = "asleep-unspecified",
        ),
        SourceCodedValue(
            source = "STAGE_TYPE_OUT_OF_BED",
            code = "STAGE_TYPE_OUT_OF_BED",
            display = "Out of bed",
            shared = "out-of-bed",
        ),
        SourceCodedValue(
            source = "STAGE_TYPE_LIGHT",
            code = "STAGE_TYPE_LIGHT",
            display = "Light sleep",
            shared = "light",
        ),
        SourceCodedValue(
            source = "STAGE_TYPE_DEEP",
            code = "STAGE_TYPE_DEEP",
            display = "Deep sleep",
            shared = "deep",
        ),
        SourceCodedValue(
            source = "STAGE_TYPE_REM",
            code = "STAGE_TYPE_REM",
            display = "REM sleep",
            shared = "rem",
        ),
        SourceCodedValue(
            source = "STAGE_TYPE_AWAKE_IN_BED",
            code = "STAGE_TYPE_AWAKE_IN_BED",
            display = "Awake in bed",
            shared = "awake",
        ),
    ),
)

private val HEALTH_CONNECT_MENSTRUATION_FLOW: SourceCodedMapping = SourceCodedMapping(
    sourceSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-menstruation-flow",
    appliesToMeasurement = "menstruation-flow",
    values = listOf(
        SourceCodedValue(
            source = "FLOW_UNKNOWN",
            code = "FLOW_UNKNOWN",
            display = "Unknown",
            shared = "unspecified",
        ),
        SourceCodedValue(
            source = "FLOW_LIGHT",
            code = "FLOW_LIGHT",
            display = "Light",
            shared = "light",
        ),
        SourceCodedValue(
            source = "FLOW_MEDIUM",
            code = "FLOW_MEDIUM",
            display = "Medium",
            shared = "medium",
        ),
        SourceCodedValue(
            source = "FLOW_HEAVY",
            code = "FLOW_HEAVY",
            display = "Heavy",
            shared = "heavy",
        ),
    ),
)

private val HEALTH_CONNECT_OVULATION_TEST_RESULT: SourceCodedMapping = SourceCodedMapping(
    sourceSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-ovulation-test-result",
    appliesToMeasurement = "ovulation-test-result",
    values = listOf(
        SourceCodedValue(
            source = "RESULT_NEGATIVE",
            code = "RESULT_NEGATIVE",
            display = "Negative",
            shared = "negative",
        ),
        SourceCodedValue(
            source = "RESULT_HIGH",
            code = "RESULT_HIGH",
            display = "High",
            shared = "high-fertility",
        ),
        SourceCodedValue(
            source = "RESULT_POSITIVE",
            code = "RESULT_POSITIVE",
            display = "Positive",
            shared = "luteinizing-hormone-surge",
        ),
        SourceCodedValue(
            source = "RESULT_INCONCLUSIVE",
            code = "RESULT_INCONCLUSIVE",
            display = "Inconclusive",
            shared = "indeterminate",
        ),
    ),
)

private val HEALTH_CONNECT_SEXUAL_ACTIVITY_PROTECTION: SourceCodedMapping = SourceCodedMapping(
    sourceSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-sexual-activity-protection",
    appliesToMeasurement = "sexual-activity",
    values = listOf(
        SourceCodedValue(
            source = "PROTECTION_USED_UNKNOWN",
            code = "PROTECTION_USED_UNKNOWN",
            display = "Unknown",
            shared = "unknown",
        ),
        SourceCodedValue(
            source = "PROTECTION_USED_PROTECTED",
            code = "PROTECTION_USED_PROTECTED",
            display = "Protected",
            shared = "protected",
        ),
        SourceCodedValue(
            source = "PROTECTION_USED_UNPROTECTED",
            code = "PROTECTION_USED_UNPROTECTED",
            display = "Unprotected",
            shared = "unprotected",
        ),
    ),
)

private val HEALTH_CONNECT_CERVICAL_MUCUS_APPEARANCE: SourceCodedMapping = SourceCodedMapping(
    sourceSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-cervical-mucus-appearance",
    appliesToMeasurement = "cervical-mucus-quality",
    values = listOf(
        SourceCodedValue(
            source = "APPEARANCE_UNKNOWN",
            code = "APPEARANCE_UNKNOWN",
            display = "Unknown",
            shared = "unknown",
        ),
        SourceCodedValue(
            source = "APPEARANCE_DRY",
            code = "APPEARANCE_DRY",
            display = "Dry",
            shared = "dry",
        ),
        SourceCodedValue(
            source = "APPEARANCE_STICKY",
            code = "APPEARANCE_STICKY",
            display = "Sticky",
            shared = "sticky",
        ),
        SourceCodedValue(
            source = "APPEARANCE_CREAMY",
            code = "APPEARANCE_CREAMY",
            display = "Creamy",
            shared = "creamy",
        ),
        SourceCodedValue(
            source = "APPEARANCE_WATERY",
            code = "APPEARANCE_WATERY",
            display = "Watery",
            shared = "watery",
        ),
        SourceCodedValue(
            source = "APPEARANCE_EGG_WHITE",
            code = "APPEARANCE_EGG_WHITE",
            display = "Egg white",
            shared = "egg-white",
        ),
        SourceCodedValue(
            source = "APPEARANCE_UNUSUAL",
            code = "APPEARANCE_UNUSUAL",
            display = "Unusual",
            shared = "unusual",
        ),
    ),
)

private val HEALTH_CONNECT_CERVICAL_MUCUS_SENSATION: SourceCodedMapping = SourceCodedMapping(
    sourceSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-cervical-mucus-sensation",
    appliesToMeasurement = "cervical-mucus-quality",
    values = listOf(
        SourceCodedValue(
            source = "SENSATION_LIGHT",
            code = "SENSATION_LIGHT",
            display = "Light",
            shared = "light",
        ),
        SourceCodedValue(
            source = "SENSATION_MEDIUM",
            code = "SENSATION_MEDIUM",
            display = "Medium",
            shared = "medium",
        ),
        SourceCodedValue(
            source = "SENSATION_HEAVY",
            code = "SENSATION_HEAVY",
            display = "Heavy",
            shared = "heavy",
        ),
    ),
)

private val HEALTH_CONNECT_MINDFULNESS_SESSION_TYPE: SourceOnlyMapping = SourceOnlyMapping(
    codeSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-mindfulness-session-type",
    values = listOf(
        SourceOnlyValue(
            source = "MINDFULNESS_SESSION_TYPE_UNKNOWN",
            code = "MINDFULNESS_SESSION_TYPE_UNKNOWN",
            display = "Unknown",
        ),
        SourceOnlyValue(
            source = "MINDFULNESS_SESSION_TYPE_MEDITATION",
            code = "MINDFULNESS_SESSION_TYPE_MEDITATION",
            display = "Meditation",
        ),
        SourceOnlyValue(
            source = "MINDFULNESS_SESSION_TYPE_BREATHING",
            code = "MINDFULNESS_SESSION_TYPE_BREATHING",
            display = "Guided breathing",
        ),
        SourceOnlyValue(
            source = "MINDFULNESS_SESSION_TYPE_MUSIC",
            code = "MINDFULNESS_SESSION_TYPE_MUSIC",
            display = "Music or soundscapes",
        ),
        SourceOnlyValue(
            source = "MINDFULNESS_SESSION_TYPE_MOVEMENT",
            code = "MINDFULNESS_SESSION_TYPE_MOVEMENT",
            display = "Movement",
        ),
        SourceOnlyValue(
            source = "MINDFULNESS_SESSION_TYPE_UNGUIDED",
            code = "MINDFULNESS_SESSION_TYPE_UNGUIDED",
            display = "Unguided",
        ),
    ),
)

private val HEALTH_CONNECT_VO2_MAX_MEASUREMENT_METHOD: SourceOnlyMapping = SourceOnlyMapping(
    codeSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-vo2-max-measurement-method",
    values = listOf(
        SourceOnlyValue(
            source = "MEASUREMENT_METHOD_OTHER",
            code = "MEASUREMENT_METHOD_OTHER",
            display = "Other",
        ),
        SourceOnlyValue(
            source = "MEASUREMENT_METHOD_METABOLIC_CART",
            code = "MEASUREMENT_METHOD_METABOLIC_CART",
            display = "Metabolic cart",
        ),
        SourceOnlyValue(
            source = "MEASUREMENT_METHOD_HEART_RATE_RATIO",
            code = "MEASUREMENT_METHOD_HEART_RATE_RATIO",
            display = "Heart-rate ratio",
        ),
        SourceOnlyValue(
            source = "MEASUREMENT_METHOD_COOPER_TEST",
            code = "MEASUREMENT_METHOD_COOPER_TEST",
            display = "Cooper test",
        ),
        SourceOnlyValue(
            source = "MEASUREMENT_METHOD_MULTISTAGE_FITNESS_TEST",
            code = "MEASUREMENT_METHOD_MULTISTAGE_FITNESS_TEST",
            display = "Multistage fitness test",
        ),
        SourceOnlyValue(
            source = "MEASUREMENT_METHOD_ROCKPORT_FITNESS_TEST",
            code = "MEASUREMENT_METHOD_ROCKPORT_FITNESS_TEST",
            display = "Rockport fitness test",
        ),
    ),
)

private val HEALTH_CONNECT_RELATION_TO_MEAL: SourceOnlyMapping = SourceOnlyMapping(
    codeSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-relation-to-meal",
    values = listOf(
        SourceOnlyValue(
            source = "RELATION_TO_MEAL_GENERAL",
            code = "RELATION_TO_MEAL_GENERAL",
            display = "General",
        ),
        SourceOnlyValue(
            source = "RELATION_TO_MEAL_FASTING",
            code = "RELATION_TO_MEAL_FASTING",
            display = "Fasting",
        ),
        SourceOnlyValue(
            source = "RELATION_TO_MEAL_BEFORE_MEAL",
            code = "RELATION_TO_MEAL_BEFORE_MEAL",
            display = "Before meal",
        ),
        SourceOnlyValue(
            source = "RELATION_TO_MEAL_AFTER_MEAL",
            code = "RELATION_TO_MEAL_AFTER_MEAL",
            display = "After meal",
        ),
    ),
)

private val HEALTH_CONNECT_MEAL_TYPE: SourceOnlyMapping = SourceOnlyMapping(
    codeSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-meal-type",
    values = listOf(
        SourceOnlyValue(
            source = "MEAL_TYPE_BREAKFAST",
            code = "MEAL_TYPE_BREAKFAST",
            display = "Breakfast",
        ),
        SourceOnlyValue(
            source = "MEAL_TYPE_LUNCH",
            code = "MEAL_TYPE_LUNCH",
            display = "Lunch",
        ),
        SourceOnlyValue(
            source = "MEAL_TYPE_DINNER",
            code = "MEAL_TYPE_DINNER",
            display = "Dinner",
        ),
        SourceOnlyValue(
            source = "MEAL_TYPE_SNACK",
            code = "MEAL_TYPE_SNACK",
            display = "Snack",
        ),
    ),
)

private val HEALTH_CONNECT_BLOOD_PRESSURE_BODY_POSITION: ExternalCodedMapping = ExternalCodedMapping(
    values = listOf(
        ExternalCodedValue(
            source = "BODY_POSITION_UNKNOWN",
            coding = null,
        ),
        ExternalCodedValue(
            source = "BODY_POSITION_STANDING_UP",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "10904000",
                display = "Orthostatic body position",
            ),
        ),
        ExternalCodedValue(
            source = "BODY_POSITION_SITTING_DOWN",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "33586001",
                display = "Sitting position",
            ),
        ),
        ExternalCodedValue(
            source = "BODY_POSITION_LYING_DOWN",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "102538003",
                display = "Recumbent body position",
            ),
        ),
        ExternalCodedValue(
            source = "BODY_POSITION_RECLINING",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "272580008",
                display = "Semi-recumbent position",
            ),
        ),
    ),
)

private val HEALTH_CONNECT_BLOOD_PRESSURE_MEASUREMENT_LOCATION: ExternalCodedMapping = ExternalCodedMapping(
    values = listOf(
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_UNKNOWN",
            coding = null,
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_LEFT_WRIST",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "5951000",
                display = "Structure of left wrist region",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_RIGHT_WRIST",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "9736006",
                display = "Structure of right wrist region",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_LEFT_UPPER_ARM",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "368208006",
                display = "Left upper arm structure",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_RIGHT_UPPER_ARM",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "368209003",
                display = "Right upper arm structure",
            ),
        ),
    ),
)

private val HEALTH_CONNECT_TEMPERATURE_MEASUREMENT_LOCATION: ExternalCodedMapping = ExternalCodedMapping(
    values = listOf(
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_UNKNOWN",
            coding = null,
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_ARMPIT",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "422543003",
                display = "Structure of axillary fossa",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_FINGER",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "7569003",
                display = "Finger structure",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_FOREHEAD",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "52795006",
                display = "Forehead structure",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_MOUTH",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "74262004",
                display = "Oral cavity structure",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_RECTUM",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "34402009",
                display = "Rectum structure",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_TEMPORAL_ARTERY",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "15672000",
                display = "Structure of superficial temporal artery",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_TOE",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "29707007",
                display = "Toe structure",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_EAR",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "117590005",
                display = "Ear structure",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_WRIST",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "8205005",
                display = "Wrist region structure",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_VAGINA",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "76784001",
                display = "Vaginal structure",
            ),
        ),
    ),
)

private val HEALTH_CONNECT_SKIN_TEMPERATURE_MEASUREMENT_LOCATION: ExternalCodedMapping = ExternalCodedMapping(
    values = listOf(
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_UNKNOWN",
            coding = null,
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_FINGER",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "7569003",
                display = "Finger structure",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_TOE",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "29707007",
                display = "Toe structure",
            ),
        ),
        ExternalCodedValue(
            source = "MEASUREMENT_LOCATION_WRIST",
            coding = CatalogCoding(
                system = "http://snomed.info/sct",
                code = "8205005",
                display = "Wrist region structure",
            ),
        ),
    ),
)

private val HEALTH_CONNECT_BLOOD_GLUCOSE_SPECIMEN: List<SpecimenSourceValue> = listOf(
    SpecimenSourceValue(
        source = "SPECIMEN_SOURCE_WHOLE_BLOOD",
        status = HealthConnectSourceStatus.SUPPORTED,
        measurement = "blood-glucose",
        specimenType = CatalogCoding(
            system = "http://snomed.info/sct",
            code = "258580003",
            display = "Whole blood specimen",
        ),
    ),
    SpecimenSourceValue(
        source = "SPECIMEN_SOURCE_CAPILLARY_BLOOD",
        status = HealthConnectSourceStatus.SUPPORTED,
        measurement = "capillary-blood-glucose",
        specimenType = CatalogCoding(
            system = "http://snomed.info/sct",
            code = "122554006",
            display = "Capillary blood specimen",
        ),
    ),
    SpecimenSourceValue(
        source = "SPECIMEN_SOURCE_PLASMA",
        status = HealthConnectSourceStatus.SUPPORTED,
        measurement = "serum-plasma-glucose",
        specimenType = CatalogCoding(
            system = "http://snomed.info/sct",
            code = "119361006",
            display = "Plasma specimen",
        ),
    ),
    SpecimenSourceValue(
        source = "SPECIMEN_SOURCE_SERUM",
        status = HealthConnectSourceStatus.SUPPORTED,
        measurement = "serum-plasma-glucose",
        specimenType = CatalogCoding(
            system = "http://snomed.info/sct",
            code = "119364003",
            display = "Serum specimen",
        ),
    ),
    SpecimenSourceValue(
        source = "SPECIMEN_SOURCE_INTERSTITIAL_FLUID",
        status = HealthConnectSourceStatus.SUPPORTED,
        measurement = "interstitial-glucose",
        specimenType = CatalogCoding(
            system = "http://snomed.info/sct",
            code = "258479004",
            display = "Interstitial fluid specimen",
        ),
    ),
    SpecimenSourceValue(
        source = "SPECIMEN_SOURCE_TEARS",
        status = HealthConnectSourceStatus.INTENTIONALLY_UNSUPPORTED,
        measurement = null,
        specimenType = null,
    ),
    SpecimenSourceValue(
        source = "SPECIMEN_SOURCE_UNKNOWN",
        status = HealthConnectSourceStatus.INTENTIONALLY_UNSUPPORTED,
        measurement = null,
        specimenType = null,
    ),
)

private val HEALTH_CONNECT_EXERCISE_TYPE: AllowedSourceCodes = AllowedSourceCodes(
    sourceSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-exercise-type",
    appliesToMeasurement = "workout",
    codes = setOf(
        "EXERCISE_TYPE_BADMINTON",
        "EXERCISE_TYPE_BASEBALL",
        "EXERCISE_TYPE_BASKETBALL",
        "EXERCISE_TYPE_BIKING",
        "EXERCISE_TYPE_BIKING_STATIONARY",
        "EXERCISE_TYPE_BOOT_CAMP",
        "EXERCISE_TYPE_BOXING",
        "EXERCISE_TYPE_CALISTHENICS",
        "EXERCISE_TYPE_CRICKET",
        "EXERCISE_TYPE_DANCING",
        "EXERCISE_TYPE_ELLIPTICAL",
        "EXERCISE_TYPE_EXERCISE_CLASS",
        "EXERCISE_TYPE_FENCING",
        "EXERCISE_TYPE_FOOTBALL_AMERICAN",
        "EXERCISE_TYPE_FOOTBALL_AUSTRALIAN",
        "EXERCISE_TYPE_FRISBEE_DISC",
        "EXERCISE_TYPE_GOLF",
        "EXERCISE_TYPE_GUIDED_BREATHING",
        "EXERCISE_TYPE_GYMNASTICS",
        "EXERCISE_TYPE_HANDBALL",
        "EXERCISE_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING",
        "EXERCISE_TYPE_HIKING",
        "EXERCISE_TYPE_ICE_HOCKEY",
        "EXERCISE_TYPE_ICE_SKATING",
        "EXERCISE_TYPE_MARTIAL_ARTS",
        "EXERCISE_TYPE_OTHER_WORKOUT",
        "EXERCISE_TYPE_PADDLING",
        "EXERCISE_TYPE_PARAGLIDING",
        "EXERCISE_TYPE_PILATES",
        "EXERCISE_TYPE_RACQUETBALL",
        "EXERCISE_TYPE_ROCK_CLIMBING",
        "EXERCISE_TYPE_ROLLER_HOCKEY",
        "EXERCISE_TYPE_ROWING",
        "EXERCISE_TYPE_ROWING_MACHINE",
        "EXERCISE_TYPE_RUGBY",
        "EXERCISE_TYPE_RUNNING",
        "EXERCISE_TYPE_RUNNING_TREADMILL",
        "EXERCISE_TYPE_SAILING",
        "EXERCISE_TYPE_SCUBA_DIVING",
        "EXERCISE_TYPE_SKATING",
        "EXERCISE_TYPE_SKIING",
        "EXERCISE_TYPE_SNOWBOARDING",
        "EXERCISE_TYPE_SNOWSHOEING",
        "EXERCISE_TYPE_SOCCER",
        "EXERCISE_TYPE_SOFTBALL",
        "EXERCISE_TYPE_SQUASH",
        "EXERCISE_TYPE_STAIR_CLIMBING",
        "EXERCISE_TYPE_STAIR_CLIMBING_MACHINE",
        "EXERCISE_TYPE_STRENGTH_TRAINING",
        "EXERCISE_TYPE_STRETCHING",
        "EXERCISE_TYPE_SURFING",
        "EXERCISE_TYPE_SWIMMING_OPEN_WATER",
        "EXERCISE_TYPE_SWIMMING_POOL",
        "EXERCISE_TYPE_TABLE_TENNIS",
        "EXERCISE_TYPE_TENNIS",
        "EXERCISE_TYPE_VOLLEYBALL",
        "EXERCISE_TYPE_WALKING",
        "EXERCISE_TYPE_WATER_POLO",
        "EXERCISE_TYPE_WEIGHTLIFTING",
        "EXERCISE_TYPE_WHEELCHAIR",
        "EXERCISE_TYPE_YOGA",
    ),
)

private val HEALTH_CONNECT_EXERCISE_SEGMENT_TYPE: AllowedSourceCodes = AllowedSourceCodes(
    sourceSystem = "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-exercise-segment-type",
    appliesToMeasurement = "workout-segment",
    codes = setOf(
        "EXERCISE_SEGMENT_TYPE_ARM_CURL",
        "EXERCISE_SEGMENT_TYPE_BACK_EXTENSION",
        "EXERCISE_SEGMENT_TYPE_BALL_SLAM",
        "EXERCISE_SEGMENT_TYPE_BARBELL_SHOULDER_PRESS",
        "EXERCISE_SEGMENT_TYPE_BENCH_PRESS",
        "EXERCISE_SEGMENT_TYPE_BENCH_SIT_UP",
        "EXERCISE_SEGMENT_TYPE_BIKING",
        "EXERCISE_SEGMENT_TYPE_BIKING_STATIONARY",
        "EXERCISE_SEGMENT_TYPE_BURPEE",
        "EXERCISE_SEGMENT_TYPE_CRUNCH",
        "EXERCISE_SEGMENT_TYPE_DEADLIFT",
        "EXERCISE_SEGMENT_TYPE_DOUBLE_ARM_TRICEPS_EXTENSION",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_CURL_LEFT_ARM",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_CURL_RIGHT_ARM",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_FRONT_RAISE",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_LATERAL_RAISE",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_ROW",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_LEFT_ARM",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_RIGHT_ARM",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_TWO_ARM",
        "EXERCISE_SEGMENT_TYPE_ELLIPTICAL",
        "EXERCISE_SEGMENT_TYPE_FORWARD_TWIST",
        "EXERCISE_SEGMENT_TYPE_FRONT_RAISE",
        "EXERCISE_SEGMENT_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING",
        "EXERCISE_SEGMENT_TYPE_HIP_THRUST",
        "EXERCISE_SEGMENT_TYPE_HULA_HOOP",
        "EXERCISE_SEGMENT_TYPE_JUMPING_JACK",
        "EXERCISE_SEGMENT_TYPE_JUMP_ROPE",
        "EXERCISE_SEGMENT_TYPE_KETTLEBELL_SWING",
        "EXERCISE_SEGMENT_TYPE_LATERAL_RAISE",
        "EXERCISE_SEGMENT_TYPE_LAT_PULL_DOWN",
        "EXERCISE_SEGMENT_TYPE_LEG_CURL",
        "EXERCISE_SEGMENT_TYPE_LEG_EXTENSION",
        "EXERCISE_SEGMENT_TYPE_LEG_PRESS",
        "EXERCISE_SEGMENT_TYPE_LEG_RAISE",
        "EXERCISE_SEGMENT_TYPE_LUNGE",
        "EXERCISE_SEGMENT_TYPE_MOUNTAIN_CLIMBER",
        "EXERCISE_SEGMENT_TYPE_OTHER_WORKOUT",
        "EXERCISE_SEGMENT_TYPE_PAUSE",
        "EXERCISE_SEGMENT_TYPE_PILATES",
        "EXERCISE_SEGMENT_TYPE_PLANK",
        "EXERCISE_SEGMENT_TYPE_PULL_UP",
        "EXERCISE_SEGMENT_TYPE_PUNCH",
        "EXERCISE_SEGMENT_TYPE_REST",
        "EXERCISE_SEGMENT_TYPE_ROWING_MACHINE",
        "EXERCISE_SEGMENT_TYPE_RUNNING",
        "EXERCISE_SEGMENT_TYPE_RUNNING_TREADMILL",
        "EXERCISE_SEGMENT_TYPE_SHOULDER_PRESS",
        "EXERCISE_SEGMENT_TYPE_SINGLE_ARM_TRICEPS_EXTENSION",
        "EXERCISE_SEGMENT_TYPE_SIT_UP",
        "EXERCISE_SEGMENT_TYPE_SQUAT",
        "EXERCISE_SEGMENT_TYPE_STAIR_CLIMBING",
        "EXERCISE_SEGMENT_TYPE_STAIR_CLIMBING_MACHINE",
        "EXERCISE_SEGMENT_TYPE_STRETCHING",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_BACKSTROKE",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_BREASTSTROKE",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_BUTTERFLY",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_FREESTYLE",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_MIXED",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_OPEN_WATER",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_OTHER",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_POOL",
        "EXERCISE_SEGMENT_TYPE_UNKNOWN",
        "EXERCISE_SEGMENT_TYPE_UPPER_TWIST",
        "EXERCISE_SEGMENT_TYPE_WALKING",
        "EXERCISE_SEGMENT_TYPE_WEIGHTLIFTING",
        "EXERCISE_SEGMENT_TYPE_WHEELCHAIR",
        "EXERCISE_SEGMENT_TYPE_YOGA",
        "EXERCISE_LAP",
    ),
)

private val CONCEPT_DISPLAYS: Map<String, Map<String, String>> = mapOf(
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-aggregation-method" to mapOf(
        "daily-total" to "Daily total",
        "daily-mean" to "Daily mean",
        "daily-minimum" to "Daily minimum",
        "daily-maximum" to "Daily maximum",
        "session-mean" to "Session mean",
        "session-total" to "Session total",
        "rolling-mean" to "Rolling mean",
        "percentage-of-time" to "Percentage of time",
        "session-minimum" to "Session minimum",
        "session-rate" to "Session rate",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-application-version-type" to mapOf(
        "build" to "Build",
        "os-version" to "Operating system version",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-cervical-mucus-quality" to mapOf(
        "dry" to "Dry",
        "sticky" to "Sticky",
        "creamy" to "Creamy",
        "watery" to "Watery",
        "egg-white" to "Egg white",
        "unusual" to "Unusual",
        "unknown" to "Unknown",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-cervical-mucus-sensation" to mapOf(
        "light" to "Light",
        "medium" to "Medium",
        "heavy" to "Heavy",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-identifier-role" to mapOf(
        "source-record" to "Source record",
        "source-output" to "Source output",
        "writer-record" to "Writer record",
        "source-artifact" to "Source artifact",
        "source-context" to "Source context",
        "recording-device" to "Recording device",
        "device-snapshot" to "Device snapshot",
        "event" to "Event",
        "entry-node" to "Entry node",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-intermenstrual-bleeding" to mapOf(
        "present" to "Present",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-lifecycle-event" to mapOf(
        "source-record-retracted" to "Source record retracted",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-menstrual-cycle-start" to mapOf(
        "cycle-start" to "Cycle start",
        "not-cycle-start" to "Not cycle start",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-menstruation-flow" to mapOf(
        "unspecified" to "Unspecified",
        "light" to "Light",
        "medium" to "Medium",
        "heavy" to "Heavy",
        "none" to "None",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-mobile-measurement" to mapOf(
        "active-energy-burned" to "Active energy burned",
        "basal-body-temperature" to "Basal body temperature",
        "basal-energy-burned" to "Basal energy burned",
        "cervical-mucus-quality" to "Cervical mucus quality",
        "cycling-cadence" to "Cycling cadence",
        "dietary-biotin" to "Dietary biotin",
        "dietary-caffeine" to "Dietary caffeine",
        "dietary-calcium" to "Dietary calcium",
        "dietary-chloride" to "Dietary chloride",
        "dietary-cholesterol" to "Dietary cholesterol",
        "dietary-chromium" to "Dietary chromium",
        "dietary-copper" to "Dietary copper",
        "dietary-fat-monounsaturated" to "Dietary monounsaturated fat",
        "dietary-fat-polyunsaturated" to "Dietary polyunsaturated fat",
        "dietary-fat-saturated" to "Dietary saturated fat",
        "dietary-fiber" to "Dietary fiber",
        "dietary-folate" to "Dietary folate",
        "dietary-iodine" to "Dietary iodine",
        "dietary-iron" to "Dietary iron",
        "dietary-magnesium" to "Dietary magnesium",
        "dietary-manganese" to "Dietary manganese",
        "dietary-molybdenum" to "Dietary molybdenum",
        "dietary-niacin" to "Dietary niacin",
        "dietary-pantothenic-acid" to "Dietary pantothenic acid",
        "dietary-phosphorus" to "Dietary phosphorus",
        "dietary-potassium" to "Dietary potassium",
        "dietary-riboflavin" to "Dietary riboflavin",
        "dietary-selenium" to "Dietary selenium",
        "dietary-sodium" to "Dietary sodium",
        "dietary-sugar" to "Dietary sugar",
        "dietary-thiamin" to "Dietary thiamin",
        "dietary-vitamin-a" to "Dietary vitamin A",
        "dietary-vitamin-b12" to "Dietary vitamin B12",
        "dietary-vitamin-b6" to "Dietary vitamin B6",
        "dietary-vitamin-c" to "Dietary vitamin C",
        "dietary-vitamin-d" to "Dietary vitamin D",
        "dietary-vitamin-e" to "Dietary vitamin E",
        "dietary-vitamin-k" to "Dietary vitamin K",
        "dietary-zinc" to "Dietary zinc",
        "electrodermal-activity" to "Electrodermal activity",
        "heart-rate-variability-rmssd" to "Heart rate variability RMSSD",
        "intermenstrual-bleeding" to "Intermenstrual bleeding",
        "menstruation-flow" to "Menstruation flow",
        "mindfulness-session-duration" to "Mindfulness session duration",
        "ovulation-test-result" to "Ovulation test result",
        "power" to "Power",
        "sexual-activity" to "Sexual activity",
        "sleep-heart-rate" to "Sleep heart rate",
        "sleep-stage" to "Sleep stage",
        "speed" to "Speed",
        "step-count-total" to "Step count total",
        "vo2-max" to "VO2 max",
        "workout" to "Workout session",
        "workout-segment" to "Workout segment",
        "cervical-mucus-sensation" to "Cervical mucus sensation",
        "menstrual-cycle-start" to "Menstrual cycle start",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-ovulation-test-result" to mapOf(
        "negative" to "Negative",
        "high-fertility" to "High fertility",
        "luteinizing-hormone-surge" to "Luteinizing hormone surge",
        "indeterminate" to "Indeterminate",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-recording-method" to mapOf(
        "manual-entry" to "Manual entry",
        "actively-recorded" to "Actively recorded",
        "automatically-recorded" to "Automatically recorded",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-retraction-target-role" to mapOf(
        "primary-output" to "Primary output",
        "source-artifact" to "Source artifact",
        "child-output" to "Child output",
        "specimen" to "Specimen",
        "device-snapshot" to "Device snapshot",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-sexual-activity" to mapOf(
        "protected" to "Protection used",
        "unprotected" to "Protection not used",
        "unknown" to "Unknown",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-sleep-stage" to mapOf(
        "awake" to "Awake",
        "in-bed" to "In bed",
        "out-of-bed" to "Out of bed",
        "asleep-unspecified" to "Asleep, unspecified stage",
        "light" to "Light sleep",
        "deep" to "Deep sleep",
        "rem" to "REM sleep",
        "unknown" to "Unknown sleep stage",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-workout-activity" to mapOf(
        "running" to "Running",
        "walking" to "Walking",
        "cycling" to "Cycling",
        "hiking" to "Hiking",
        "swimming" to "Swimming",
        "strength-training" to "Strength training",
        "high-intensity-interval-training" to "High-intensity interval training",
        "yoga" to "Yoga",
        "pilates" to "Pilates",
        "rowing" to "Rowing",
        "elliptical" to "Elliptical",
        "stair-climbing" to "Stair climbing",
        "dancing" to "Dancing",
        "tennis" to "Tennis",
        "table-tennis" to "Table tennis",
        "badminton" to "Badminton",
        "squash" to "Squash",
        "basketball" to "Basketball",
        "soccer" to "Soccer",
        "american-football" to "American football",
        "baseball" to "Baseball",
        "volleyball" to "Volleyball",
        "golf" to "Golf",
        "boxing" to "Boxing",
        "martial-arts" to "Martial arts",
        "skiing" to "Skiing",
        "snowboarding" to "Snowboarding",
        "other" to "Other activity",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-workout-segment-type" to mapOf(
        "lap" to "Lap",
        "pause" to "Pause",
        "resume" to "Resume",
        "motion-paused" to "Motion paused",
        "motion-resumed" to "Motion resumed",
        "pause-or-resume-request" to "Pause or resume request",
        "marker" to "Marker",
        "segment-generic" to "Segment",
        "rest" to "Rest",
        "other-workout" to "Other workout",
        "unknown" to "Unknown",
    ),
    "https://grovealliance.org/fhir/mobile/CodeSystem/grove-workout-statistic" to mapOf(
        "active-duration" to "Active duration",
        "distance-sum" to "Total distance",
        "active-energy-sum" to "Total active energy",
        "heart-rate-avg" to "Average heart rate",
        "heart-rate-max" to "Maximum heart rate",
        "heart-rate-min" to "Minimum heart rate",
        "step-count-sum" to "Total steps",
        "elevation-gain" to "Elevation gained",
        "flights-climbed-sum" to "Flights climbed",
        "speed-avg" to "Average speed",
        "swimming-stroke-count-sum" to "Total swimming strokes",
        "pool-lap-count" to "Pool laps",
        "repetitions" to "Repetitions",
        "set-weight" to "Set weight",
        "set-index" to "Set index",
        "rating-of-perceived-exertion" to "Rating of perceived exertion",
        "lap-length" to "Lap length",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-cervical-mucus-appearance" to mapOf(
        "APPEARANCE_UNKNOWN" to "Unknown",
        "APPEARANCE_DRY" to "Dry",
        "APPEARANCE_STICKY" to "Sticky",
        "APPEARANCE_CREAMY" to "Creamy",
        "APPEARANCE_WATERY" to "Watery",
        "APPEARANCE_EGG_WHITE" to "Egg white",
        "APPEARANCE_UNUSUAL" to "Unusual",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-cervical-mucus-sensation" to mapOf(
        "SENSATION_LIGHT" to "Light",
        "SENSATION_MEDIUM" to "Medium",
        "SENSATION_HEAVY" to "Heavy",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-concept-property" to mapOf(
        "documentation" to "Documentation",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-exercise-segment-type" to mapOf(
        "EXERCISE_SEGMENT_TYPE_ARM_CURL" to "Arm curl",
        "EXERCISE_SEGMENT_TYPE_BACK_EXTENSION" to "Back extension",
        "EXERCISE_SEGMENT_TYPE_BALL_SLAM" to "Ball slam",
        "EXERCISE_SEGMENT_TYPE_BARBELL_SHOULDER_PRESS" to "Barbell shoulder press",
        "EXERCISE_SEGMENT_TYPE_BENCH_PRESS" to "Bench press",
        "EXERCISE_SEGMENT_TYPE_BENCH_SIT_UP" to "Bench sit up",
        "EXERCISE_SEGMENT_TYPE_BIKING" to "Biking",
        "EXERCISE_SEGMENT_TYPE_BIKING_STATIONARY" to "Biking stationary",
        "EXERCISE_SEGMENT_TYPE_BURPEE" to "Burpee",
        "EXERCISE_SEGMENT_TYPE_CRUNCH" to "Crunch",
        "EXERCISE_SEGMENT_TYPE_DEADLIFT" to "Deadlift",
        "EXERCISE_SEGMENT_TYPE_DOUBLE_ARM_TRICEPS_EXTENSION" to "Double arm triceps extension",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_CURL_LEFT_ARM" to "Dumbbell curl left arm",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_CURL_RIGHT_ARM" to "Dumbbell curl right arm",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_FRONT_RAISE" to "Dumbbell front raise",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_LATERAL_RAISE" to "Dumbbell lateral raise",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_ROW" to "Dumbbell row",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_LEFT_ARM" to "Dumbbell triceps extension left arm",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_RIGHT_ARM" to "Dumbbell triceps extension right arm",
        "EXERCISE_SEGMENT_TYPE_DUMBBELL_TRICEPS_EXTENSION_TWO_ARM" to "Dumbbell triceps extension two arm",
        "EXERCISE_SEGMENT_TYPE_ELLIPTICAL" to "Elliptical",
        "EXERCISE_SEGMENT_TYPE_FORWARD_TWIST" to "Forward twist",
        "EXERCISE_SEGMENT_TYPE_FRONT_RAISE" to "Front raise",
        "EXERCISE_SEGMENT_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING" to "High intensity interval training",
        "EXERCISE_SEGMENT_TYPE_HIP_THRUST" to "Hip thrust",
        "EXERCISE_SEGMENT_TYPE_HULA_HOOP" to "Hula hoop",
        "EXERCISE_SEGMENT_TYPE_JUMPING_JACK" to "Jumping jack",
        "EXERCISE_SEGMENT_TYPE_JUMP_ROPE" to "Jump rope",
        "EXERCISE_SEGMENT_TYPE_KETTLEBELL_SWING" to "Kettlebell swing",
        "EXERCISE_SEGMENT_TYPE_LATERAL_RAISE" to "Lateral raise",
        "EXERCISE_SEGMENT_TYPE_LAT_PULL_DOWN" to "Lat pull down",
        "EXERCISE_SEGMENT_TYPE_LEG_CURL" to "Leg curl",
        "EXERCISE_SEGMENT_TYPE_LEG_EXTENSION" to "Leg extension",
        "EXERCISE_SEGMENT_TYPE_LEG_PRESS" to "Leg press",
        "EXERCISE_SEGMENT_TYPE_LEG_RAISE" to "Leg raise",
        "EXERCISE_SEGMENT_TYPE_LUNGE" to "Lunge",
        "EXERCISE_SEGMENT_TYPE_MOUNTAIN_CLIMBER" to "Mountain climber",
        "EXERCISE_SEGMENT_TYPE_OTHER_WORKOUT" to "Other workout",
        "EXERCISE_SEGMENT_TYPE_PAUSE" to "Pause",
        "EXERCISE_SEGMENT_TYPE_PILATES" to "Pilates",
        "EXERCISE_SEGMENT_TYPE_PLANK" to "Plank",
        "EXERCISE_SEGMENT_TYPE_PULL_UP" to "Pull up",
        "EXERCISE_SEGMENT_TYPE_PUNCH" to "Punch",
        "EXERCISE_SEGMENT_TYPE_REST" to "Rest",
        "EXERCISE_SEGMENT_TYPE_ROWING_MACHINE" to "Rowing machine",
        "EXERCISE_SEGMENT_TYPE_RUNNING" to "Running",
        "EXERCISE_SEGMENT_TYPE_RUNNING_TREADMILL" to "Running treadmill",
        "EXERCISE_SEGMENT_TYPE_SHOULDER_PRESS" to "Shoulder press",
        "EXERCISE_SEGMENT_TYPE_SINGLE_ARM_TRICEPS_EXTENSION" to "Single arm triceps extension",
        "EXERCISE_SEGMENT_TYPE_SIT_UP" to "Sit up",
        "EXERCISE_SEGMENT_TYPE_SQUAT" to "Squat",
        "EXERCISE_SEGMENT_TYPE_STAIR_CLIMBING" to "Stair climbing",
        "EXERCISE_SEGMENT_TYPE_STAIR_CLIMBING_MACHINE" to "Stair climbing machine",
        "EXERCISE_SEGMENT_TYPE_STRETCHING" to "Stretching",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_BACKSTROKE" to "Swimming backstroke",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_BREASTSTROKE" to "Swimming breaststroke",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_BUTTERFLY" to "Swimming butterfly",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_FREESTYLE" to "Swimming freestyle",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_MIXED" to "Swimming mixed",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_OPEN_WATER" to "Swimming open water",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_OTHER" to "Swimming other",
        "EXERCISE_SEGMENT_TYPE_SWIMMING_POOL" to "Swimming pool",
        "EXERCISE_SEGMENT_TYPE_UNKNOWN" to "Unknown",
        "EXERCISE_SEGMENT_TYPE_UPPER_TWIST" to "Upper twist",
        "EXERCISE_SEGMENT_TYPE_WALKING" to "Walking",
        "EXERCISE_SEGMENT_TYPE_WEIGHTLIFTING" to "Weightlifting",
        "EXERCISE_SEGMENT_TYPE_WHEELCHAIR" to "Wheelchair",
        "EXERCISE_SEGMENT_TYPE_YOGA" to "Yoga",
        "EXERCISE_LAP" to "Exercise lap",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-exercise-type" to mapOf(
        "EXERCISE_TYPE_BADMINTON" to "Badminton",
        "EXERCISE_TYPE_BASEBALL" to "Baseball",
        "EXERCISE_TYPE_BASKETBALL" to "Basketball",
        "EXERCISE_TYPE_BIKING" to "Biking",
        "EXERCISE_TYPE_BIKING_STATIONARY" to "Biking stationary",
        "EXERCISE_TYPE_BOOT_CAMP" to "Boot camp",
        "EXERCISE_TYPE_BOXING" to "Boxing",
        "EXERCISE_TYPE_CALISTHENICS" to "Calisthenics",
        "EXERCISE_TYPE_CRICKET" to "Cricket",
        "EXERCISE_TYPE_DANCING" to "Dancing",
        "EXERCISE_TYPE_ELLIPTICAL" to "Elliptical",
        "EXERCISE_TYPE_EXERCISE_CLASS" to "Exercise class",
        "EXERCISE_TYPE_FENCING" to "Fencing",
        "EXERCISE_TYPE_FOOTBALL_AMERICAN" to "Football american",
        "EXERCISE_TYPE_FOOTBALL_AUSTRALIAN" to "Football australian",
        "EXERCISE_TYPE_FRISBEE_DISC" to "Frisbee disc",
        "EXERCISE_TYPE_GOLF" to "Golf",
        "EXERCISE_TYPE_GUIDED_BREATHING" to "Guided breathing",
        "EXERCISE_TYPE_GYMNASTICS" to "Gymnastics",
        "EXERCISE_TYPE_HANDBALL" to "Handball",
        "EXERCISE_TYPE_HIGH_INTENSITY_INTERVAL_TRAINING" to "High intensity interval training",
        "EXERCISE_TYPE_HIKING" to "Hiking",
        "EXERCISE_TYPE_ICE_HOCKEY" to "Ice hockey",
        "EXERCISE_TYPE_ICE_SKATING" to "Ice skating",
        "EXERCISE_TYPE_MARTIAL_ARTS" to "Martial arts",
        "EXERCISE_TYPE_OTHER_WORKOUT" to "Other workout",
        "EXERCISE_TYPE_PADDLING" to "Paddling",
        "EXERCISE_TYPE_PARAGLIDING" to "Paragliding",
        "EXERCISE_TYPE_PILATES" to "Pilates",
        "EXERCISE_TYPE_RACQUETBALL" to "Racquetball",
        "EXERCISE_TYPE_ROCK_CLIMBING" to "Rock climbing",
        "EXERCISE_TYPE_ROLLER_HOCKEY" to "Roller hockey",
        "EXERCISE_TYPE_ROWING" to "Rowing",
        "EXERCISE_TYPE_ROWING_MACHINE" to "Rowing machine",
        "EXERCISE_TYPE_RUGBY" to "Rugby",
        "EXERCISE_TYPE_RUNNING" to "Running",
        "EXERCISE_TYPE_RUNNING_TREADMILL" to "Running treadmill",
        "EXERCISE_TYPE_SAILING" to "Sailing",
        "EXERCISE_TYPE_SCUBA_DIVING" to "Scuba diving",
        "EXERCISE_TYPE_SKATING" to "Skating",
        "EXERCISE_TYPE_SKIING" to "Skiing",
        "EXERCISE_TYPE_SNOWBOARDING" to "Snowboarding",
        "EXERCISE_TYPE_SNOWSHOEING" to "Snowshoeing",
        "EXERCISE_TYPE_SOCCER" to "Soccer",
        "EXERCISE_TYPE_SOFTBALL" to "Softball",
        "EXERCISE_TYPE_SQUASH" to "Squash",
        "EXERCISE_TYPE_STAIR_CLIMBING" to "Stair climbing",
        "EXERCISE_TYPE_STAIR_CLIMBING_MACHINE" to "Stair climbing machine",
        "EXERCISE_TYPE_STRENGTH_TRAINING" to "Strength training",
        "EXERCISE_TYPE_STRETCHING" to "Stretching",
        "EXERCISE_TYPE_SURFING" to "Surfing",
        "EXERCISE_TYPE_SWIMMING_OPEN_WATER" to "Swimming open water",
        "EXERCISE_TYPE_SWIMMING_POOL" to "Swimming pool",
        "EXERCISE_TYPE_TABLE_TENNIS" to "Table tennis",
        "EXERCISE_TYPE_TENNIS" to "Tennis",
        "EXERCISE_TYPE_VOLLEYBALL" to "Volleyball",
        "EXERCISE_TYPE_WALKING" to "Walking",
        "EXERCISE_TYPE_WATER_POLO" to "Water polo",
        "EXERCISE_TYPE_WEIGHTLIFTING" to "Weightlifting",
        "EXERCISE_TYPE_WHEELCHAIR" to "Wheelchair",
        "EXERCISE_TYPE_YOGA" to "Yoga",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-meal-type" to mapOf(
        "MEAL_TYPE_BREAKFAST" to "Breakfast",
        "MEAL_TYPE_LUNCH" to "Lunch",
        "MEAL_TYPE_DINNER" to "Dinner",
        "MEAL_TYPE_SNACK" to "Snack",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-measurement" to mapOf(
        "basal-metabolic-rate" to "Basal metabolic rate",
        "dietary-energy-from-fat" to "Nutrition energy from fat",
        "dietary-fat-trans" to "Nutrition trans fat",
        "dietary-fat-unsaturated" to "Nutrition unsaturated fat",
        "dietary-folic-acid" to "Nutrition folic acid",
        "elevation-gained" to "Elevation gained",
        "menstruation-period" to "Menstruation period",
        "step-cadence" to "Step cadence",
        "total-energy-burned" to "Total energy burned",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-menstruation-flow" to mapOf(
        "FLOW_UNKNOWN" to "Unknown",
        "FLOW_LIGHT" to "Light",
        "FLOW_MEDIUM" to "Medium",
        "FLOW_HEAVY" to "Heavy",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-menstruation-period" to mapOf(
        "present" to "Present",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-mindfulness-session-type" to mapOf(
        "MINDFULNESS_SESSION_TYPE_UNKNOWN" to "Unknown",
        "MINDFULNESS_SESSION_TYPE_MEDITATION" to "Meditation",
        "MINDFULNESS_SESSION_TYPE_BREATHING" to "Guided breathing",
        "MINDFULNESS_SESSION_TYPE_MUSIC" to "Music or soundscapes",
        "MINDFULNESS_SESSION_TYPE_MOVEMENT" to "Movement",
        "MINDFULNESS_SESSION_TYPE_UNGUIDED" to "Unguided",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-ovulation-test-result" to mapOf(
        "RESULT_NEGATIVE" to "Negative",
        "RESULT_HIGH" to "High",
        "RESULT_POSITIVE" to "Positive",
        "RESULT_INCONCLUSIVE" to "Inconclusive",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-record-type" to mapOf(
        "ActiveCaloriesBurnedRecord" to "Active Calories Burned",
        "BasalBodyTemperatureRecord" to "Basal Body Temperature",
        "BasalMetabolicRateRecord" to "Basal Metabolic Rate",
        "BloodGlucoseRecord" to "Blood Glucose",
        "BloodPressureRecord" to "Blood Pressure",
        "BodyFatRecord" to "Body Fat",
        "BodyTemperatureRecord" to "Body Temperature",
        "BodyWaterMassRecord" to "Body Water Mass",
        "BoneMassRecord" to "Bone Mass",
        "CervicalMucusRecord" to "Cervical Mucus",
        "CyclingPedalingCadenceRecord" to "Cycling Pedaling Cadence",
        "DistanceRecord" to "Distance",
        "ElevationGainedRecord" to "Elevation Gained",
        "ExerciseSessionRecord" to "Exercise Session",
        "FloorsClimbedRecord" to "Floors Climbed",
        "HeartRateRecord" to "Heart Rate",
        "HeartRateVariabilityRmssdRecord" to "Heart Rate Variability RMSSD",
        "HeightRecord" to "Height",
        "HydrationRecord" to "Hydration",
        "IntermenstrualBleedingRecord" to "Intermenstrual Bleeding",
        "LeanBodyMassRecord" to "Lean Body Mass",
        "MenstruationFlowRecord" to "Menstruation Flow",
        "MenstruationPeriodRecord" to "Menstruation Period",
        "MindfulnessSessionRecord" to "Mindfulness Session",
        "NutritionRecord" to "Nutrition",
        "OvulationTestRecord" to "Ovulation Test",
        "OxygenSaturationRecord" to "Oxygen Saturation",
        "PlannedExerciseSessionRecord" to "Planned Exercise Session",
        "PowerRecord" to "Power",
        "RespiratoryRateRecord" to "Respiratory Rate",
        "RestingHeartRateRecord" to "Resting Heart Rate",
        "SexualActivityRecord" to "Sexual Activity",
        "SkinTemperatureRecord" to "Skin Temperature",
        "SleepSessionRecord" to "Sleep Session",
        "SpeedRecord" to "Speed",
        "StepsCadenceRecord" to "Steps Cadence",
        "StepsRecord" to "Steps",
        "TotalCaloriesBurnedRecord" to "Total Calories Burned",
        "Vo2MaxRecord" to "VO2 Max",
        "WeightRecord" to "Weight",
        "WheelchairPushesRecord" to "Wheelchair Pushes",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-relation-to-meal" to mapOf(
        "RELATION_TO_MEAL_GENERAL" to "General",
        "RELATION_TO_MEAL_FASTING" to "Fasting",
        "RELATION_TO_MEAL_BEFORE_MEAL" to "Before meal",
        "RELATION_TO_MEAL_AFTER_MEAL" to "After meal",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-sexual-activity-protection" to mapOf(
        "PROTECTION_USED_UNKNOWN" to "Unknown",
        "PROTECTION_USED_PROTECTED" to "Protected",
        "PROTECTION_USED_UNPROTECTED" to "Unprotected",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-sleep-stage" to mapOf(
        "STAGE_TYPE_UNKNOWN" to "Unknown",
        "STAGE_TYPE_AWAKE" to "Awake",
        "STAGE_TYPE_SLEEPING" to "Sleeping",
        "STAGE_TYPE_OUT_OF_BED" to "Out of bed",
        "STAGE_TYPE_LIGHT" to "Light sleep",
        "STAGE_TYPE_DEEP" to "Deep sleep",
        "STAGE_TYPE_REM" to "REM sleep",
        "STAGE_TYPE_AWAKE_IN_BED" to "Awake in bed",
    ),
    "https://grovealliance.org/fhir/health-connect/CodeSystem/health-connect-vo2-max-measurement-method" to mapOf(
        "MEASUREMENT_METHOD_OTHER" to "Other",
        "MEASUREMENT_METHOD_METABOLIC_CART" to "Metabolic cart",
        "MEASUREMENT_METHOD_HEART_RATE_RATIO" to "Heart-rate ratio",
        "MEASUREMENT_METHOD_COOPER_TEST" to "Cooper test",
        "MEASUREMENT_METHOD_MULTISTAGE_FITNESS_TEST" to "Multistage fitness test",
        "MEASUREMENT_METHOD_ROCKPORT_FITNESS_TEST" to "Rockport fitness test",
    ),
)
