//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT

// Generated by Scripts/generate-grove-fhir-kotlin-contract.py. Do not edit by hand.

package org.grovealliance.health.fhir

import org.grovealliance.fhir.ExchangeContract

/** Canonicals the Health Connect adapter emits, projected from the grove-fhir catalogs. */
public object HealthConnectContract {
    public const val HEALTH_CONNECT_BASE: String = "${ExchangeContract.CANONICAL_ROOT}/health-connect"
    public const val MOBILE_BASE: String = ExchangeContract.MOBILE_BASE

    /** The AndroidX artifact whose Record inventory this adapter converts. */
    public const val SOURCE_PACKAGE: String = "androidx.health.connect:connect-client"
    public const val SOURCE_VERSION: String = "1.1.0"
    public const val RECORD_TYPE_COUNT: Int = 41

    /** The adapter-id component of every Health Connect opaque identity. */
    public const val ADAPTER_ID: String = "health-connect"

    /** The largest writer record version the contract admits. */
    public const val WRITER_RECORD_VERSION_MAXIMUM: Long = 9223372036854775807L

    public const val HEALTH_CONNECT_OBSERVATION_PROFILE: String =
        "https://grovealliance.org/fhir/health-connect/StructureDefinition/health-connect-observation"
    public const val HEALTH_CONNECT_SPECIMEN_PROFILE: String =
        "https://grovealliance.org/fhir/health-connect/StructureDefinition/health-connect-specimen"
    public const val HEALTH_CONNECT_PROVENANCE_PROFILE: String =
        "https://grovealliance.org/fhir/health-connect/StructureDefinition/health-connect-conversion-provenance"

    public const val MOBILE_ACTIVE_ENERGY_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-active-energy"
    public const val MOBILE_BASAL_BODY_TEMPERATURE_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-basal-body-temperature"
    public const val MOBILE_BLOOD_PRESSURE_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-blood-pressure"
    public const val MOBILE_BODY_FAT_PERCENTAGE_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-body-fat-percentage"
    public const val MOBILE_BODY_HEIGHT_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-body-height"
    public const val MOBILE_BODY_TEMPERATURE_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-body-temperature"
    public const val MOBILE_BODY_WATER_MASS_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-body-water-mass"
    public const val MOBILE_BODY_WEIGHT_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-body-weight"
    public const val MOBILE_BONE_MASS_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-bone-mass"
    public const val MOBILE_CERVICAL_MUCUS_QUALITY_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-cervical-mucus-quality"
    public const val MOBILE_CYCLING_CADENCE_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-cycling-cadence"
    public const val MOBILE_DISTANCE_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-distance"
    public const val MOBILE_FLIGHTS_CLIMBED_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-flights-climbed"
    public const val MOBILE_FLUID_INTAKE_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-fluid-intake"
    public const val MOBILE_HEART_RATE_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-heart-rate"
    public const val MOBILE_HEART_RATE_VARIABILITY_RMSSD_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-heart-rate-variability-rmssd"
    public const val MOBILE_INTERMENSTRUAL_BLEEDING_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-intermenstrual-bleeding"
    public const val MOBILE_LEAN_BODY_MASS_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-lean-body-mass"
    public const val MOBILE_MENSTRUATION_FLOW_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-menstruation-flow"
    public const val MOBILE_MINDFULNESS_SESSION_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-mindfulness-session"
    public const val MOBILE_OVULATION_TEST_RESULT_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-ovulation-test-result"
    public const val MOBILE_OXYGEN_SATURATION_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-oxygen-saturation"
    public const val MOBILE_POWER_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-power"
    public const val MOBILE_RESPIRATORY_RATE_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-respiratory-rate"
    public const val MOBILE_RESTING_HEART_RATE_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-resting-heart-rate"
    public const val MOBILE_SEXUAL_ACTIVITY_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-sexual-activity"
    public const val MOBILE_SKIN_TEMPERATURE_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-skin-temperature"
    public const val MOBILE_SLEEP_DURATION_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-sleep-duration"
    public const val MOBILE_SLEEP_STAGE_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-sleep-stage"
    public const val MOBILE_SPEED_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-speed"
    public const val MOBILE_STEP_COUNT_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-step-count"
    public const val MOBILE_VO2_MAX_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-vo2-max"
    public const val MOBILE_WHEELCHAIR_PUSH_COUNT_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-wheelchair-push-count"
    public const val MOBILE_WORKOUT_PROFILE: String = "$MOBILE_BASE/StructureDefinition/grove-mobile-workout"
    public const val MOBILE_WORKOUT_SEGMENT_PROFILE: String =
        "$MOBILE_BASE/StructureDefinition/grove-mobile-workout-segment"

    public const val HEALTH_CONNECT_BASAL_METABOLIC_RATE_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-basal-metabolic-rate"
    public const val HEALTH_CONNECT_WHOLE_BLOOD_GLUCOSE_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-whole-blood-glucose"
    public const val HEALTH_CONNECT_CAPILLARY_BLOOD_GLUCOSE_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-capillary-blood-glucose"
    public const val HEALTH_CONNECT_DIETARY_ENERGY_FROM_FAT_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-dietary-energy-from-fat"
    public const val HEALTH_CONNECT_DIETARY_FAT_TRANS_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-dietary-fat-trans"
    public const val HEALTH_CONNECT_DIETARY_FAT_UNSATURATED_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-dietary-fat-unsaturated"
    public const val HEALTH_CONNECT_DIETARY_FOLIC_ACID_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-dietary-folic-acid"
    public const val HEALTH_CONNECT_ELEVATION_GAINED_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-elevation-gained"
    public const val HEALTH_CONNECT_INTERSTITIAL_GLUCOSE_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-interstitial-glucose"
    public const val HEALTH_CONNECT_MENSTRUATION_PERIOD_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-menstruation-period"
    public const val HEALTH_CONNECT_SERUM_PLASMA_GLUCOSE_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-serum-plasma-glucose"
    public const val HEALTH_CONNECT_STEP_CADENCE_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-step-cadence"
    public const val HEALTH_CONNECT_TOTAL_ENERGY_PROFILE: String =
        "$HEALTH_CONNECT_BASE/StructureDefinition/health-connect-total-energy"

    /** Every dietary nutrient the adapter emits, keyed by its catalog measurement id. */
    public val mobileDietaryProfiles: Map<String, String> = mapOf(
        "dietary-biotin" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-biotin",
        "dietary-caffeine" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-caffeine",
        "dietary-calcium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-calcium",
        "dietary-carbohydrates" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-carbohydrates",
        "dietary-chloride" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-chloride",
        "dietary-cholesterol" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-cholesterol",
        "dietary-chromium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-chromium",
        "dietary-copper" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-copper",
        "dietary-energy" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-energy",
        "dietary-fat-monounsaturated" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-fat-monounsaturated",
        "dietary-fat-polyunsaturated" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-fat-polyunsaturated",
        "dietary-fat-saturated" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-fat-saturated",
        "dietary-fat-total" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-fat-total",
        "dietary-fiber" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-fiber",
        "dietary-folate" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-folate",
        "dietary-iodine" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-iodine",
        "dietary-iron" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-iron",
        "dietary-magnesium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-magnesium",
        "dietary-manganese" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-manganese",
        "dietary-molybdenum" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-molybdenum",
        "dietary-niacin" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-niacin",
        "dietary-pantothenic-acid" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-pantothenic-acid",
        "dietary-phosphorus" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-phosphorus",
        "dietary-potassium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-potassium",
        "dietary-protein" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-protein",
        "dietary-riboflavin" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-riboflavin",
        "dietary-selenium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-selenium",
        "dietary-sodium" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-sodium",
        "dietary-sugar" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-sugar",
        "dietary-thiamin" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-thiamin",
        "dietary-vitamin-a" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-a",
        "dietary-vitamin-b12" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-b12",
        "dietary-vitamin-b6" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-b6",
        "dietary-vitamin-c" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-c",
        "dietary-vitamin-d" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-d",
        "dietary-vitamin-e" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-e",
        "dietary-vitamin-k" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-vitamin-k",
        "dietary-zinc" to "$MOBILE_BASE/StructureDefinition/grove-mobile-dietary-zinc",
    )

    /** Profiles the shared Mobile package owns, which this adapter also claims. */
    public val sharedMeasurementProfiles: Set<String> = setOf(
        MOBILE_ACTIVE_ENERGY_PROFILE,
        MOBILE_BASAL_BODY_TEMPERATURE_PROFILE,
        MOBILE_BLOOD_PRESSURE_PROFILE,
        MOBILE_BODY_FAT_PERCENTAGE_PROFILE,
        MOBILE_BODY_HEIGHT_PROFILE,
        MOBILE_BODY_TEMPERATURE_PROFILE,
        MOBILE_BODY_WATER_MASS_PROFILE,
        MOBILE_BODY_WEIGHT_PROFILE,
        MOBILE_BONE_MASS_PROFILE,
        MOBILE_CERVICAL_MUCUS_QUALITY_PROFILE,
        MOBILE_CYCLING_CADENCE_PROFILE,
        MOBILE_DISTANCE_PROFILE,
        MOBILE_FLIGHTS_CLIMBED_PROFILE,
        MOBILE_FLUID_INTAKE_PROFILE,
        MOBILE_HEART_RATE_PROFILE,
        MOBILE_HEART_RATE_VARIABILITY_RMSSD_PROFILE,
        MOBILE_INTERMENSTRUAL_BLEEDING_PROFILE,
        MOBILE_LEAN_BODY_MASS_PROFILE,
        MOBILE_MENSTRUATION_FLOW_PROFILE,
        MOBILE_MINDFULNESS_SESSION_PROFILE,
        MOBILE_OVULATION_TEST_RESULT_PROFILE,
        MOBILE_OXYGEN_SATURATION_PROFILE,
        MOBILE_POWER_PROFILE,
        MOBILE_RESPIRATORY_RATE_PROFILE,
        MOBILE_RESTING_HEART_RATE_PROFILE,
        MOBILE_SEXUAL_ACTIVITY_PROFILE,
        MOBILE_SKIN_TEMPERATURE_PROFILE,
        MOBILE_SLEEP_DURATION_PROFILE,
        MOBILE_SLEEP_STAGE_PROFILE,
        MOBILE_SPEED_PROFILE,
        MOBILE_STEP_COUNT_PROFILE,
        MOBILE_VO2_MAX_PROFILE,
        MOBILE_WHEELCHAIR_PUSH_COUNT_PROFILE,
        MOBILE_WORKOUT_PROFILE,
        MOBILE_WORKOUT_SEGMENT_PROFILE,
    ) + mobileDietaryProfiles.values

    /** Profiles only this adapter publishes. */
    public val adapterSpecificObservationProfiles: Set<String> = setOf(
        HEALTH_CONNECT_BASAL_METABOLIC_RATE_PROFILE,
        HEALTH_CONNECT_WHOLE_BLOOD_GLUCOSE_PROFILE,
        HEALTH_CONNECT_CAPILLARY_BLOOD_GLUCOSE_PROFILE,
        HEALTH_CONNECT_DIETARY_ENERGY_FROM_FAT_PROFILE,
        HEALTH_CONNECT_DIETARY_FAT_TRANS_PROFILE,
        HEALTH_CONNECT_DIETARY_FAT_UNSATURATED_PROFILE,
        HEALTH_CONNECT_DIETARY_FOLIC_ACID_PROFILE,
        HEALTH_CONNECT_ELEVATION_GAINED_PROFILE,
        HEALTH_CONNECT_INTERSTITIAL_GLUCOSE_PROFILE,
        HEALTH_CONNECT_MENSTRUATION_PERIOD_PROFILE,
        HEALTH_CONNECT_SERUM_PLASMA_GLUCOSE_PROFILE,
        HEALTH_CONNECT_STEP_CADENCE_PROFILE,
        HEALTH_CONNECT_TOTAL_ENERGY_PROFILE,
    )

    /** The Identifier.system of the Android package name that names the writer of a record. */
    public const val WRITER_PACKAGE_SYSTEM: String =
        "https://grovealliance.org/fhir/health-connect/NamingSystem/android-package-name"
    public const val RECORDING_METHOD_EXTENSION: String = "$MOBILE_BASE/StructureDefinition/grove-recording-method"
    public const val HEALTH_CONNECT_SESSION_TITLE: String =
        "https://grovealliance.org/fhir/health-connect/StructureDefinition/health-connect-session-title"
    public const val HEALTH_CONNECT_GLUCOSE_MEAL_CONTEXT: String =
        "https://grovealliance.org/fhir/health-connect/StructureDefinition/health-connect-glucose-meal-context"
    public const val HEALTH_CONNECT_RECORD_TYPE_EXTENSION: String =
        "https://grovealliance.org/fhir/health-connect/StructureDefinition/health-connect-record-type"

    public const val GROVE_AGGREGATION_METHOD: String = "$MOBILE_BASE/CodeSystem/grove-aggregation-method"
    public const val GROVE_APPLICATION_VERSION_TYPE: String = "$MOBILE_BASE/CodeSystem/grove-application-version-type"
    public const val GROVE_CERVICAL_MUCUS_QUALITY: String = "$MOBILE_BASE/CodeSystem/grove-cervical-mucus-quality"
    public const val GROVE_CERVICAL_MUCUS_SENSATION: String = "$MOBILE_BASE/CodeSystem/grove-cervical-mucus-sensation"
    public const val GROVE_IDENTIFIER_ROLE: String = "$MOBILE_BASE/CodeSystem/grove-identifier-role"
    public const val GROVE_INTERMENSTRUAL_BLEEDING: String = "$MOBILE_BASE/CodeSystem/grove-intermenstrual-bleeding"
    public const val GROVE_LIFECYCLE_EVENT: String = "$MOBILE_BASE/CodeSystem/grove-lifecycle-event"
    public const val GROVE_MENSTRUAL_CYCLE_START: String = "$MOBILE_BASE/CodeSystem/grove-menstrual-cycle-start"
    public const val GROVE_MENSTRUATION_FLOW: String = "$MOBILE_BASE/CodeSystem/grove-menstruation-flow"
    public const val GROVE_MOBILE_MEASUREMENT: String = "$MOBILE_BASE/CodeSystem/grove-mobile-measurement"
    public const val GROVE_OVULATION_TEST_RESULT: String = "$MOBILE_BASE/CodeSystem/grove-ovulation-test-result"
    public const val GROVE_RECORDING_METHOD: String = "$MOBILE_BASE/CodeSystem/grove-recording-method"
    public const val GROVE_SEXUAL_ACTIVITY: String = "$MOBILE_BASE/CodeSystem/grove-sexual-activity"
    public const val GROVE_SLEEP_STAGE: String = "$MOBILE_BASE/CodeSystem/grove-sleep-stage"
    public const val GROVE_WORKOUT_ACTIVITY: String = "$MOBILE_BASE/CodeSystem/grove-workout-activity"
    public const val GROVE_WORKOUT_SEGMENT_TYPE: String = "$MOBILE_BASE/CodeSystem/grove-workout-segment-type"
    public const val GROVE_WORKOUT_STATISTIC: String = "$MOBILE_BASE/CodeSystem/grove-workout-statistic"
    public const val HEALTH_CONNECT_CERVICAL_MUCUS_APPEARANCE: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-cervical-mucus-appearance"
    public const val HEALTH_CONNECT_CERVICAL_MUCUS_SENSATION: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-cervical-mucus-sensation"
    public const val HEALTH_CONNECT_CONCEPT_PROPERTY: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-concept-property"
    public const val HEALTH_CONNECT_EXERCISE_SEGMENT_TYPE: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-exercise-segment-type"
    public const val HEALTH_CONNECT_EXERCISE_TYPE: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-exercise-type"
    public const val HEALTH_CONNECT_MEAL_TYPE: String = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-meal-type"
    public const val HEALTH_CONNECT_MEASUREMENT: String = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-measurement"
    public const val HEALTH_CONNECT_MENSTRUATION_FLOW: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-menstruation-flow"
    public const val HEALTH_CONNECT_MENSTRUATION_PERIOD: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-menstruation-period"
    public const val HEALTH_CONNECT_MINDFULNESS_SESSION_TYPE: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-mindfulness-session-type"
    public const val HEALTH_CONNECT_OVULATION_TEST_RESULT: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-ovulation-test-result"
    public const val HEALTH_CONNECT_RECORD_TYPE: String = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-record-type"
    public const val HEALTH_CONNECT_RELATION_TO_MEAL: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-relation-to-meal"
    public const val HEALTH_CONNECT_SEXUAL_ACTIVITY_PROTECTION: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-sexual-activity-protection"
    public const val HEALTH_CONNECT_SLEEP_STAGE: String = "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-sleep-stage"
    public const val HEALTH_CONNECT_VO2_MAX_MEASUREMENT_METHOD: String =
        "$HEALTH_CONNECT_BASE/CodeSystem/health-connect-vo2-max-measurement-method"

    public const val OBSERVATION_BODY_POSITION: String =
        "http://hl7.org/fhir/StructureDefinition/observation-bodyPosition"
    public const val LOINC: String = "http://loinc.org"
    public const val SNOMED_CT: String = "http://snomed.info/sct"
    public const val UCUM: String = "http://unitsofmeasure.org"
    public const val MDC: String = "urn:iso:std:iso:11073:10101"

    /** The ISO 11073 MDC software-revision code. */
    public const val APPLICATION_SOFTWARE_VERSION: String = "531975"
    public const val OBSERVATION_CATEGORY: String = "http://terminology.hl7.org/CodeSystem/observation-category"
}
