#
# This source file is part of the Grove open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

default_platform(:android)

platform :android do
  desc "Runs all unit tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Verifies screenshots against their recorded baselines"
  lane :screenshotTests do
    gradle(task: "verifyPaparazziDebug")
  end

  desc "Runs all UI tests"
  lane :connectedCheck do
    gradle(task: "connectedCheck")
  end
end
