#!/usr/bin/env python3
"""Project the Grove FHIR catalogs onto the Kotlin contract and adapter modules.

Every catalog-owned fact the Kotlin producers dispatch on is generated here, so a catalog change
that reaches Swift and TypeScript cannot silently miss Kotlin: the exchange-protocol lexemes,
identity kinds and roles, the closed rule registry, the recommended identifier-system forms, the
study-context roles, the Health Connect source types, outputs, measurements and context
mappings, and the vendored conformance vectors the tests execute.
"""

# This source file is part of the Grove open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any

HEADER = """//
// This source file is part of the Grove open-source project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT

// Generated by Scripts/generate-grove-fhir-kotlin-contract.py. Do not edit by hand.

"""

LICENSE_SIDECAR = """Generated by Scripts/generate-grove-fhir-kotlin-contract.py from the grove-fhir
{source}. Do not edit by hand.

SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)

SPDX-License-Identifier: MIT
"""

CONTRACT_PACKAGE = "org.grovealliance.fhir"
ADAPTER_PACKAGE = "org.grovealliance.health.fhir"
CONTRACT_SOURCES = Path("fhir-contract/src/main/kotlin/org/grovealliance/fhir")
CONTRACT_TEST_RESOURCES = Path("fhir-contract/src/test/resources")
ADAPTER_SOURCES = Path("health-fhir/src/main/kotlin/org/grovealliance/health/fhir")
ADAPTER_TEST_RESOURCES = Path("health-fhir/src/test/resources")

HEALTH_CONNECT_CANONICAL = "https://grovealliance.org/fhir/health-connect"
MOBILE_CANONICAL = "https://grovealliance.org/fhir/mobile"
ISO_LIFECYCLE = "http://terminology.hl7.org/CodeSystem/iso-21089-lifecycle"
PROVENANCE_PARTICIPANT = "http://terminology.hl7.org/CodeSystem/provenance-participant-type"
OBSERVATION_CATEGORY = "http://terminology.hl7.org/CodeSystem/observation-category"

# Canonicals the adapter needs that no catalog owns, because they belong to HL7 or a
# terminology authority rather than to Grove.
EXTERNAL_SYSTEMS: list[tuple[str, str, str]] = [
    ("OBSERVATION_BODY_POSITION", "http://hl7.org/fhir/StructureDefinition/observation-bodyPosition", ""),
    ("LOINC", "http://loinc.org", ""),
    ("SNOMED_CT", "http://snomed.info/sct", ""),
    ("UCUM", "http://unitsofmeasure.org", ""),
    ("MDC", "urn:iso:std:iso:11073:10101", ""),
    ("APPLICATION_SOFTWARE_VERSION", "531975", "The ISO 11073 MDC software-revision code."),
    ("OBSERVATION_CATEGORY", OBSERVATION_CATEGORY, ""),
]

EQUALITY_SEQUENCES = ("reformatted-replay", "lexeme-replay")
EFFECTIVE_SHAPES = {"dateTime": "DATE_TIME", "Period": "PERIOD", "dateTime-or-Period": "DATE_TIME_OR_PERIOD"}
LINE_WIDTH = 100


class Catalogs:
    def __init__(self, catalog_directory: Path) -> None:
        self.directory = catalog_directory
        self.repository = catalog_directory.parent
        self.measurements = self.load("measurement-catalog.json")
        self.health_connect = self.load("health-connect-adapter.json")
        self.graph = self.load("package-graph.json")
        self.protocol = self.load("exchange-protocol.json")
        self.claims = self.load("profile-claims.json")
        self.providers = self.load("providers-adapter.json")
        self.healthkit = self.load("healthkit-adapter.json")
        self.sensorkit = self.load("sensorkit-adapter.json")
        self.formats = self.load("format-registry.json")

    def load(self, name: str) -> dict[str, Any]:
        return json.loads((self.directory / name).read_text(encoding="utf-8"))


# --- Kotlin rendering helpers -------------------------------------------------------------------


def kotlin_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("$", "\\$")
    return f'"{escaped}"'


def wrapped_string(value: str, indent: int) -> str:
    """Render one string as `+` joined chunks so no generated line exceeds the lint limit."""
    if len(value) <= LINE_WIDTH:
        return kotlin_string(value)
    chunks: list[str] = []
    current = ""
    for word in value.split(" "):
        candidate = word if not current else f"{current} {word}"
        if len(candidate) > LINE_WIDTH and current:
            chunks.append(current + " ")
            current = word
        else:
            current = candidate
    chunks.append(current)
    joiner = " +\n" + " " * indent
    return joiner.join(kotlin_string(chunk) for chunk in chunks)


def constant_name(identifier: str, suffix: str = "", prefix: str | None = None, strip: str | None = None) -> str:
    """`grove-mobile-heart-rate` becomes `MOBILE_HEART_RATE_PROFILE`."""
    stem = re.sub(strip or r"^(grove-mobile-|grove-|health-connect-)", "", identifier)
    if prefix is None:
        prefix = "MOBILE" if identifier.startswith(("grove-mobile-", "grove-")) else "HEALTH_CONNECT"
    body = re.sub(r"[^A-Za-z0-9]+", "_", stem).strip("_").upper()
    return f"{prefix}_{body}{suffix}"


def enum_name(token: str) -> str:
    """`ActiveCaloriesBurned`, `active-calories-burned` and `Vo2Max` all become upper snake case."""
    spaced = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", token)
    return re.sub(r"[^A-Za-z0-9]+", "_", spaced).strip("_").upper()


def constant_type(value: str) -> str:
    if value.startswith('"') or value.startswith("$") or "." in value and not value.rstrip("L").isdigit():
        return "String"
    if value.endswith("L") and value[:-1].isdigit():
        return "Long"
    if value.isdigit():
        return "Int"
    raise SystemExit(f"cannot infer the constant type of {value!r}")


def declaration(name: str, value: str, doc: str = "", visibility: str = "public ") -> str:
    line = f"    {visibility}const val {name}: {constant_type(value)} = {value}"
    prefix = f"\n    /** {doc} */\n" if doc else ""
    if len(line) <= 120:
        return prefix + line
    return prefix + f"    {visibility}const val {name}: {constant_type(value)} =\n        {value}"


def string_set(name: str, values: list[str], indent: int = 4, visibility: str = "public ") -> list[str]:
    pad = " " * indent
    lines = [f"{pad}{visibility}val {name}: Set<String> = setOf("]
    lines.extend(f"{pad}    {kotlin_string(value)}," for value in values)
    lines.append(f"{pad})")
    return lines


def kotlin_decimal(value: int | float | None) -> str:
    if value is None:
        return "null"
    return f"java.math.BigDecimal({kotlin_string(json.dumps(value, allow_nan=False))})"


def render_coding(coding: dict[str, Any], indent: int) -> str:
    display = coding.get("display")
    pad = " " * indent
    return (
        "CatalogCoding(\n"
        f"{pad}    system = {kotlin_string(coding['system'])},\n"
        f"{pad}    code = {kotlin_string(coding['code'])},\n"
        f"{pad}    display = {kotlin_string(display) if display else 'null'},\n"
        f"{pad})"
    )


def render_value_domain(domain: dict[str, Any], indent: int) -> str:
    pad = " " * indent
    minimum = domain.get("minimum")
    maximum = domain.get("maximum")
    return (
        "QuantityValueDomain(\n"
        f"{pad}    minimum = {kotlin_decimal(minimum.get('value') if minimum else None)},\n"
        f"{pad}    maximum = {kotlin_decimal(maximum.get('value') if maximum else None)},\n"
        f"{pad}    integerOnly = {str(domain.get('integerOnly', False)).lower()},\n"
        f"{pad})"
    )


# --- FSH terminology ----------------------------------------------------------------------------


def fsh_code_systems(guide_directory: Path) -> dict[str, list[tuple[str, str]]]:
    """Every CodeSystem a guide publishes with its concepts, read from the FSH sources."""
    fsh = guide_directory / "input" / "fsh"
    sources = sorted(fsh.glob("*.fsh"))
    if not sources:
        raise SystemExit(f"{fsh} holds no FSH; the contract cannot be projected from it")
    found: dict[str, list[tuple[str, str]]] = {}
    for source in sources:
        declared: str | None = None
        identifier: str | None = None
        for line in source.read_text(encoding="utf-8").splitlines():
            header = re.match(r"^CodeSystem:\s+(\S+)", line)
            if header:
                if declared and identifier is None:
                    raise SystemExit(f"{source}: CodeSystem {declared} declares no Id")
                declared, identifier = header.group(1), None
                continue
            if re.match(r"^[A-Za-z]+:\s", line) and not line.startswith(("Id:", "Title:", "Description:")):
                if declared and identifier is None:
                    raise SystemExit(f"{source}: CodeSystem {declared} declares no Id")
                declared, identifier = None, None
                continue
            if declared and line.startswith("Id:"):
                identifier = line.split(":", 1)[1].strip()
                found.setdefault(identifier, [])
                continue
            concept = re.match(r'^\* #(\S+) "((?:[^"\\]|\\.)*)"', line)
            if declared and identifier and concept:
                found[identifier].append((concept.group(1), concept.group(2).replace('\\"', '"')))
        if declared and identifier is None:
            raise SystemExit(f"{source}: CodeSystem {declared} declares no Id")
    if not found:
        raise SystemExit(f"{fsh} declares no CodeSystem; the contract would silently lose them")
    return dict(sorted(found.items()))


def concept_displays(code_systems: dict[str, list[tuple[str, str]]], identifier: str) -> dict[str, str]:
    concepts = code_systems.get(identifier)
    if not concepts:
        raise SystemExit(f"CodeSystem {identifier} declares no concepts")
    return dict(concepts)


# --- Contract projections -----------------------------------------------------------------------


def identity_roles(catalogs: Catalogs, displays: dict[str, str]) -> list[tuple[str, str]]:
    roles: list[str] = []
    for kind in catalogs.protocol["opaqueIdentity"]["identityKinds"]:
        role = kind["identifierRole"]
        if role not in roles:
            roles.append(role)
    roles.extend(role for role in ("event", "entry-node") if role not in roles)
    return [(role, displays[role]) for role in roles]


def identity_kinds(catalogs: Catalogs) -> list[dict[str, Any]]:
    kinds = catalogs.protocol["opaqueIdentity"]["identityKinds"]
    names = [row.get("kind") for row in kinds]
    if len(set(names)) != len(names) or any(not isinstance(name, str) for name in names):
        raise SystemExit("The exchange protocol identity kinds must be unique tokens")
    return kinds


def unsigned_decimal_components(catalogs: Catalogs) -> list[str]:
    opaque = catalogs.protocol["opaqueIdentity"]
    names = opaque["componentRequirements"].get("unsignedDecimal")
    declared = {component for kind in opaque["identityKinds"] for component in kind["components"]}
    if not isinstance(names, list) or not names or len(set(names)) != len(names) or not set(names) <= declared:
        raise SystemExit("componentRequirements.unsignedDecimal must name distinct identity-kind components")
    return names


def recommended_forms(catalogs: Catalogs) -> dict[str, str]:
    protocol = catalogs.protocol
    forms = {
        "OPAQUE_IDENTITY_SYSTEM_FORM": protocol["opaqueIdentity"].get("recommendedSystemForm"),
        "EVENT_IDENTITY_SYSTEM_FORM": protocol["event"]["bundleIdentifier"].get("recommendedSystemForm"),
        "ENTRY_NODE_IDENTITY_SYSTEM_FORM": protocol["entryIdentity"]["entryNode"].get("recommendedSystemForm"),
    }
    for name, form in forms.items():
        if not isinstance(form, str) or "<deployment-root>" not in form:
            raise SystemExit(f"The exchange protocol must declare {name} with a <deployment-root> placeholder")
    if "<identity-kind>" not in forms["OPAQUE_IDENTITY_SYSTEM_FORM"]:
        raise SystemExit("The opaque identity system form must carry the <identity-kind> placeholder")
    return forms


def value_form_prefix(value_form: Any, label: str) -> str:
    if not isinstance(value_form, str):
        raise SystemExit(f"The exchange protocol must declare a {label} value form")
    prefix = value_form.split(":", 1)[0]
    if re.fullmatch(r"[a-z][a-z0-9]*", prefix) is None:
        raise SystemExit(f"The {label} value form must start with a lowercase protocol token")
    return prefix


def protocol_string(value: Any, label: str, pattern: str) -> str:
    if not isinstance(value, str) or re.fullmatch(pattern, value) is None:
        raise SystemExit(f"The exchange protocol must declare a well-formed {label}")
    return value


def adapter_only_output_profiles(catalogs: Catalogs) -> dict[str, str]:
    contract = catalogs.protocol["lifecycle"]["active"]["adapterOnlyOutputProfileClaims"]
    if contract.get("authority") != "catalog/profile-claims.json":
        raise SystemExit("adapterOnlyOutputProfileClaims must name catalog/profile-claims.json as its authority")
    resource_types = contract.get("resourceTypes")
    if not isinstance(resource_types, list) or len(resource_types) != len(set(resource_types)):
        raise SystemExit("adapterOnlyOutputProfileClaims.resourceTypes must be a unique string list")
    candidates: dict[str, list[dict[str, Any]]] = {resource_type: [] for resource_type in resource_types}

    def visit(value: Any) -> None:
        if isinstance(value, dict):
            resource_type = value.get("resourceType")
            if resource_type in candidates and isinstance(value.get("profile"), str):
                candidates[resource_type].append(value)
            for child in value.values():
                visit(child)
        elif isinstance(value, list):
            for child in value:
                visit(child)

    visit(catalogs.claims)
    profiles: dict[str, str] = {}
    for resource_type in resource_types:
        matches = candidates[resource_type]
        if len(matches) != 1:
            raise SystemExit(f"{resource_type}: expected exactly one adapter-only claim, found {len(matches)}")
        claim = matches[0]
        if claim.get("cardinality") != 1 or claim.get("otherProfilesAllowed") is not False:
            raise SystemExit(f"{resource_type}: adapter-only claim must require one exact profile and no others")
        profiles[resource_type] = claim["profile"]
    return dict(sorted(profiles.items()))


def measurement_canonical(catalogs: Catalogs, measurement: dict[str, Any]) -> str:
    owner = measurement.get("owner", "mobile")
    return f"{catalogs.graph['canonicalRoot']}/{owner}/StructureDefinition/{measurement['profile']}"


def profile_claims(catalogs: Catalogs) -> dict[str, Any]:
    claims = catalogs.claims
    protocol = catalogs.protocol
    active = protocol["lifecycle"]["active"]
    device_modes: dict[str, list[str]] = {}
    for claim in claims["activeDeviceClaims"]:
        profiles = claim.get("profiles")
        if (
            claim.get("resourceType") != "Device"
            or claim.get("cardinality") != 1
            or claim.get("otherProfilesAllowed") is not False
            or not isinstance(profiles, list)
            or len(profiles) != 1
        ):
            raise SystemExit("Every active Device claim must be one exact closed profile")
        device_modes[profiles[0]] = claim.get("requiredIdentifierRoles", [])
    document_modes: list[tuple[list[str], list[str]]] = []
    for key in (
        "sensorRecordingDocumentClaim",
        "healthKitRecordingDocumentClaim",
        "healthKitClinicalRecordDocumentClaim",
        "sensorKitRecordingDocumentClaim",
        "providerRecordingDocumentClaim",
    ):
        claim = claims[key]
        profiles = claim.get("profiles")
        if (
            claim.get("resourceType", "DocumentReference") != "DocumentReference"
            or claim.get("cardinality") != len(profiles or [])
            or claim.get("otherProfilesAllowed") is not False
            or not profiles
        ):
            raise SystemExit("Every active DocumentReference claim must be an exact closed profile set")
        document_modes.append((sorted(profiles), claim.get("requiredIdentifierRoles", [])))
    questionnaire = claims["activeQuestionnaireResponseClaim"]
    if questionnaire.get("cardinality") != 1 or len(questionnaire.get("profiles", [])) != 1:
        raise SystemExit("The active QuestionnaireResponse claim must be one exact closed profile")
    retraction_target_roles = protocol["lifecycle"]["retraction"]["targetRoles"]
    for role, rule in retraction_target_roles.items():
        if not re.fullmatch(r"[a-z][a-z0-9-]*", role) or not rule.get("resourceTypes"):
            raise SystemExit(f"{role}: invalid retraction target-role rule")
    priority = protocol["entryIdentity"]["resourceIdentifierPriority"]
    roles = {row["identifierRole"] for row in protocol["opaqueIdentity"]["identityKinds"]}
    if len(priority) != len(set(priority)) or any(role not in roles for role in priority):
        raise SystemExit("entryIdentity.resourceIdentifierPriority must be a unique closed role list")
    observation_claim = claims["observationAdapterClaim"]
    semantic = {measurement_canonical(catalogs, row) for row in catalogs.measurements["measurements"]}
    semantic.update(observation_claim.get("sharedSensorProfiles", []))
    semantic.update(entry["semanticProfile"] for entry in observation_claim.get("standardAdapterClaims", []))
    single_profile = set(claims["healthKitSingleProfileObservationClaims"]["profiles"])
    single_profile.update(claims["healthConnectPlatformExclusiveClaims"]["profiles"])
    single_profile.update(claims["sensorKitPlatformExclusiveClaims"]["profiles"])
    device_profiles = {claim["id"]: claim["profiles"][0] for claim in claims["activeDeviceClaims"]}
    return {
        "outputResourceTypes": active["entryResourcePolicy"]["outputResourceTypes"],
        "supportingResourceTypes": active["entryResourcePolicy"]["supportingResourceTypes"],
        "lifecycleResourceType": active["entryResourcePolicy"]["lifecycleResourceType"],
        "deviceModes": dict(sorted(device_modes.items())),
        "documentModes": sorted(document_modes),
        "questionnaireProfile": questionnaire["profiles"][0],
        "provenanceProfiles": sorted(
            {protocol["profiles"]["conversionProvenance"]}
            | {claim["profile"] for claim in claims["adapterConversionProvenanceClaims"]}
        ),
        "adapterObservationProfiles": sorted(observation_claim["adapterProfiles"]),
        "semanticObservationProfiles": sorted(semantic),
        "singleProfileObservationClaims": sorted(single_profile),
        "hybridObservationProfiles": sorted(claims["sensorKitHybridObservationClaims"]["profiles"]),
        "entryIdentifierPriority": priority,
        "retractionTargetRoles": dict(sorted(retraction_target_roles.items())),
        "applicationDeviceProfile": device_profiles["mobile-application-device"],
        "hostDeviceProfile": device_profiles["mobile-host-device"],
        "recordingDeviceProfile": device_profiles["mobile-recording-device"],
    }


NON_ADAPTER_SOURCES = {"mobile", "questionnaire", "sensor"}


def known_adapter_profiles(catalogs: Catalogs) -> set[str]:
    return {
        f"{package['canonical']}/StructureDefinition/{profile}"
        for package in catalogs.graph["packages"]
        if package["source"] not in NON_ADAPTER_SOURCES
        for profile in package["profiles"]
    }


def adapter_source_markers(catalogs: Catalogs) -> dict[str, list[str]]:
    """Every adapter source-marker extension URL to the adapter profiles that admit it."""
    known = known_adapter_profiles(catalogs)

    def prefixed(adapter: str) -> list[str]:
        prefix = f"{catalogs.graph['canonicalRoot']}/{adapter}/StructureDefinition/"
        return sorted(profile for profile in known if profile.startswith(prefix))

    providers = catalogs.providers
    provider_profiles = sorted(provider["observationProfile"] for provider in providers["providers"])
    markers = {
        catalogs.healthkit["sourceTypeExtension"]["url"]: prefixed("healthkit"),
        catalogs.health_connect["sourceTypeExtension"]["url"]: prefixed("health-connect"),
        providers["sourceTypeExtension"]["url"]: provider_profiles,
        providers["providerExtension"]["url"]: provider_profiles,
        catalogs.sensorkit["sourceTypeExtension"]["url"]: prefixed("sensorkit"),
    }
    for url, profiles in markers.items():
        if not profiles:
            raise SystemExit(f"{url}: the source marker admits no adapter profile")
    return markers


def adapter_conversion_provenance_claims(catalogs: Catalogs) -> list[dict[str, Any]]:
    rows = catalogs.claims["adapterConversionProvenanceClaims"]
    for row in rows:
        if not re.fullmatch(r"[a-z][a-z-]*", row["adapter"]) or not row.get("targetAdapterProfiles"):
            raise SystemExit(f"{row.get('profile')}: malformed adapter conversion Provenance claim")
    return sorted(rows, key=lambda row: row["adapter"])


def recording_formats(catalogs: Catalogs) -> dict[str, list[str]]:
    registry = catalogs.formats
    result: dict[str, list[str]] = {}
    for code, entry in registry["formats"].items():
        content_types = entry.get("contentTypes", [entry.get("contentType")])
        if not re.fullmatch(r"[a-z][a-z0-9-]*", code) or not all(isinstance(item, str) and item for item in content_types):
            raise SystemExit(f"{code}: malformed recording format registry entry")
        result[code] = list(content_types)
    return result


def governed_source_identifier_policy(catalogs: Catalogs) -> dict[str, Any]:
    policy = catalogs.protocol["governedSourceIdentifier"]["validation"]
    designated = policy["designatedNode"]
    return {
        "maxPerPrimaryOutput": int(designated["maxPerPrimaryOutput"]),
        "maxPrimaryOutputsPerEvent": int(designated["maxPrimaryOutputsPerEvent"]),
        "neverResourceTypes": sorted(policy["neverResourceTypes"]),
        "neverProfiles": sorted(policy["neverProfiles"]),
    }


def quantity_semantics(catalogs: Catalogs) -> dict[str, tuple[str, str]]:
    result: dict[str, tuple[str, str]] = {}
    for row in catalogs.measurements["measurements"]:
        quantity = row.get("quantity")
        if isinstance(quantity, dict):
            result[measurement_canonical(catalogs, row)] = (quantity["system"], quantity["code"])
    for row in catalogs.health_connect["adapterMeasurements"]:
        quantity = row.get("quantity")
        if isinstance(quantity, dict):
            result[row["profile"]] = (quantity["system"], quantity["code"])
    return dict(sorted(result.items()))


def value_domain(quantity: Any) -> dict[str, Any] | None:
    domain = quantity.get("valueDomain") if isinstance(quantity, dict) else None
    if not isinstance(domain, dict):
        return None
    for label in ("minimum", "maximum"):
        boundary = domain.get(label)
        if boundary is not None and boundary.get("inclusive") is not True:
            raise SystemExit(f"exclusive {label} cannot be projected by QuantityValueDomain")
    return domain


def rule_rows(catalogs: Catalogs) -> list[dict[str, Any]]:
    rows = catalogs.protocol["producerDiagnostics"]
    codes = [row["code"] for row in rows]
    if len(set(codes)) != len(codes):
        raise SystemExit("exchange-protocol producer diagnostic codes must be unique")
    for row in rows:
        if row.get("severity", "error") not in ("error", "warning"):
            raise SystemExit(f"{row['code']}: unknown severity {row.get('severity')!r}")
        if not re.fullmatch(r"[a-z][a-z0-9-]*\.[a-z][a-z0-9-]*", row["code"]):
            raise SystemExit(f"{row['code']}: rule codes are <namespace>.<rule> tokens")
    return rows


# --- Generated contract sources -----------------------------------------------------------------


def generate_exchange_contract(catalogs: Catalogs) -> str:
    protocol = catalogs.protocol
    mobile_systems = fsh_code_systems(catalogs.repository / "mobile")
    role_displays = concept_displays(mobile_systems, "grove-identifier-role")
    target_displays = concept_displays(mobile_systems, "grove-retraction-target-role")
    lifecycle_displays = concept_displays(mobile_systems, "grove-lifecycle-event")
    roles = identity_roles(catalogs, role_displays)
    kinds = identity_kinds(catalogs)
    claims = profile_claims(catalogs)
    forms = recommended_forms(catalogs)
    governed_policy = governed_source_identifier_policy(catalogs)
    opaque = protocol["opaqueIdentity"]
    entry_node = protocol["entryIdentity"]["entryNode"]
    full_url = protocol["entryIdentity"]["fullUrl"]
    event_identifier = protocol["event"]["bundleIdentifier"]
    lifecycle = protocol["lifecycle"]
    study_roles = lifecycle["active"]["studyContext"]["entryNodeRoles"]
    if lifecycle["active"]["activitySystem"] != ISO_LIFECYCLE:
        raise SystemExit("The active lifecycle activity system is no longer the ISO 21089 record lifecycle")
    if lifecycle["retraction"]["activitySystem"] != protocol["codeSystems"]["lifecycleEvent"]:
        raise SystemExit("The retraction lifecycle activity system must be the Grove lifecycle-event CodeSystem")
    retraction_code = lifecycle["retraction"]["activityCode"]
    if retraction_code not in lifecycle_displays:
        raise SystemExit(f"The Grove lifecycle-event CodeSystem declares no {retraction_code} concept")
    provider_codes = sorted(row["id"] for row in catalogs.providers["providers"])
    key_minimum = opaque["keyRequirements"]["minimumBytes"]
    if not isinstance(key_minimum, int) or key_minimum < 1:
        raise SystemExit("The opaque identity key minimum must be a positive byte count")
    extension_targets = {row["url"]: row["targetTypes"] for row in protocol["referencePolicy"]["extensionTargets"]}
    research_study = next(url for url in extension_targets if url.endswith("workflow-researchStudy"))
    gateway_device = next(url for url in extension_targets if url.endswith("observation-gatewayDevice"))
    domain_pattern = r"[a-z][a-z0-9.\-]*"
    uuid_pattern = r"[0-9a-f]{8}-[0-9a-f]{4}-5[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}"

    lines: list[str] = [
        f"package {CONTRACT_PACKAGE}",
        "",
        "import org.hl7.fhir.r4.model.ResourceType",
        "",
        "/** Canonicals of the Grove Mobile exchange protocol, projected from the grove-fhir catalogs. */",
        "public object ExchangeContract {",
        declaration("FHIR_VERSION", kotlin_string(catalogs.measurements["fhirVersion"])),
        declaration("PACKAGE_VERSION", kotlin_string(catalogs.measurements["version"])),
        declaration("CANONICAL_ROOT", kotlin_string(catalogs.graph["canonicalRoot"])),
        declaration("MOBILE_BASE", '"$CANONICAL_ROOT/mobile"'),
        declaration(
            "OPAQUE_IDENTITY_DOMAIN",
            kotlin_string(protocol_string(opaque.get("domain"), "opaque identity domain", domain_pattern)),
            "Domain separator framed into every Grove opaque-identity HMAC preimage.",
        ),
        declaration(
            "OPAQUE_IDENTITY_PREFIX",
            kotlin_string(value_form_prefix(opaque.get("valueForm"), "opaque identity")),
            "Leading protocol token of every opaque identity value.",
        ),
        declaration(
            "OPAQUE_IDENTITY_MINIMUM_KEY_BYTES",
            str(key_minimum),
            "Fewest secret bytes an opaque identity key may hold.",
        ),
        declaration(
            "EVENT_IDENTITY_PREFIX",
            kotlin_string(value_form_prefix(event_identifier.get("valueForm"), "event identifier")),
            "Leading protocol token of every clear event Bundle identifier value.",
        ),
        declaration(
            "ENTRY_NODE_DOMAIN",
            kotlin_string(protocol_string(entry_node.get("domain"), "entry-node domain", domain_pattern)),
            "Domain separator framed into every entry-node digest preimage.",
        ),
        declaration(
            "ENTRY_NODE_IDENTITY_PREFIX",
            kotlin_string(value_form_prefix(entry_node.get("valueForm"), "entry-node identifier")),
            "Leading protocol token of every deterministic entry-node identifier value.",
        ),
        declaration(
            "ENTRY_FULL_URL_NAMESPACE",
            kotlin_string(protocol_string(full_url.get("namespace"), "fullUrl UUID namespace", uuid_pattern)),
            "UUIDv5 namespace over the length-framed entry Identifier pair.",
        ),
        declaration(
            "DEPLOYMENT_ROOT_PLACEHOLDER",
            '"<deployment-root>"',
            "The deployment-root placeholder every recommended identifier-system form starts with.",
        ),
        declaration("IDENTITY_KIND_PLACEHOLDER", '"<identity-kind>"'),
        declaration("KEY_ID_PLACEHOLDER", '"<key-id>"'),
        declaration("EPOCH_PLACEHOLDER", '"<epoch>"'),
    ]
    for name, form in forms.items():
        lines.append(declaration(name, kotlin_string(form), "Recommended identifier-system form from the protocol."))
    lines.extend(
        [
            "",
            declaration("MOBILE_EXCHANGE_BUNDLE_PROFILE", kotlin_string(protocol["profiles"]["activeBundle"])),
            declaration("MOBILE_RETRACTION_BUNDLE_PROFILE", kotlin_string(protocol["profiles"]["retractionBundle"])),
            declaration(
                "MOBILE_CONVERSION_PROVENANCE_PROFILE",
                kotlin_string(protocol["profiles"]["conversionProvenance"]),
            ),
            declaration(
                "MOBILE_RETRACTION_PROVENANCE_PROFILE",
                kotlin_string(protocol["profiles"]["retractionProvenance"]),
            ),
            declaration("MOBILE_APPLICATION_DEVICE_PROFILE", kotlin_string(claims["applicationDeviceProfile"])),
            declaration("MOBILE_HOST_DEVICE_PROFILE", kotlin_string(claims["hostDeviceProfile"])),
            declaration("MOBILE_RECORDING_DEVICE_PROFILE", kotlin_string(claims["recordingDeviceProfile"])),
            declaration("ACTIVE_QUESTIONNAIRE_RESPONSE_PROFILE", kotlin_string(claims["questionnaireProfile"])),
            "",
            declaration("ENTRY_NODE_KEY_EXTENSION", kotlin_string(protocol["extensions"]["entryNodeKey"])),
            declaration(
                "RETRACTION_TARGET_ROLE_EXTENSION",
                kotlin_string(protocol["extensions"]["retractionTargetRole"]),
            ),
            declaration(
                "RETRACTION_TARGET_NATIVE_IDENTIFIER_EXTENSION",
                kotlin_string(protocol["extensions"]["retractionTargetNativeIdentifier"]),
            ),
            declaration(
                "WRITER_RECORD_VERSION_EXTENSION",
                kotlin_string(protocol["extensions"]["writerRecordVersion"]),
            ),
            declaration("RESEARCH_STUDY_EXTENSION", kotlin_string(research_study)),
            declaration("GATEWAY_DEVICE_EXTENSION", kotlin_string(gateway_device)),
            "",
            declaration("GROVE_IDENTIFIER_ROLE", kotlin_string(protocol["codeSystems"]["identifierRole"])),
            declaration("GROVE_LIFECYCLE_EVENT", kotlin_string(protocol["codeSystems"]["lifecycleEvent"])),
            declaration(
                "GROVE_RETRACTION_TARGET_ROLE",
                kotlin_string(protocol["codeSystems"]["retractionTargetRole"]),
            ),
            declaration("RECORD_LIFECYCLE", kotlin_string(ISO_LIFECYCLE)),
            declaration("PROVENANCE_PARTICIPANT", kotlin_string(PROVENANCE_PARTICIPANT)),
            declaration("MDC", '"urn:iso:std:iso:11073:10101"'),
            declaration(
                "APPLICATION_SOFTWARE_VERSION",
                '"531975"',
                "The ISO 11073 MDC software-revision code an application version is typed with.",
            ),
            *[
                declaration(constant_name(identifier, prefix="GROVE", strip=r"^grove-"), f'"$MOBILE_BASE/CodeSystem/{identifier}"')
                for identifier in mobile_systems
                if identifier in ("grove-application-version-type",)
            ],
            declaration(
                "ACTIVE_LIFECYCLE_ACTIVITY_CODE",
                kotlin_string(lifecycle["active"]["activityCode"]),
                "The ISO 21089 lifecycle code of every active conversion Provenance.",
            ),
            declaration("RETRACTION_ACTIVITY_CODE", kotlin_string(retraction_code)),
            declaration("RETRACTION_ACTIVITY_DISPLAY", kotlin_string(lifecycle_displays[retraction_code])),
            declaration("ACTIVE_LIFECYCLE_RESOURCE_TYPE", kotlin_string(claims["lifecycleResourceType"])),
            declaration(
                "RECORDING_FORMAT_SYSTEM",
                kotlin_string(catalogs.formats["codeSystem"]),
                "The CodeSystem every recording DocumentReference content format is drawn from.",
            ),
            declaration(
                "HEALTH_CONNECT_WRITER_PACKAGE_SYSTEM",
                kotlin_string(catalogs.health_connect["dataOriginApplication"]["identifierSystem"]),
                "The Identifier.system of the Android package name that names a Health Connect writer.",
            ),
            "",
            "    /** Closed provider codes admitted by the provider-specific HMAC identity domains. */",
            *string_set("providerCodes", provider_codes),
            "",
            "    /** Opaque identity components whose value must be a canonical unsigned decimal. */",
            *string_set("unsignedDecimalComponents", unsigned_decimal_components(catalogs)),
            "",
            "    /** Closed resource types admitted in a Mobile active event graph. */",
            *string_set("activeOutputResourceTypes", claims["outputResourceTypes"]),
            *string_set("activeSupportingResourceTypes", claims["supportingResourceTypes"]),
            "",
            "    /** Catalog-priority business Identifier used as each exchange entry key. */",
            "    public val entryIdentifierPriority: List<GroveIdentifierRole> = listOf(",
            *[f"        GroveIdentifierRole.{enum_name(role)}," for role in claims["entryIdentifierPriority"]],
            "    )",
            "",
            "    /** Exact Device profile mode to its exact typed Grove identifier roles. */",
            "    public val activeDeviceProfileClaims: Map<String, Set<GroveIdentifierRole>> = mapOf(",
        ]
    )
    for profile, role_list in claims["deviceModes"].items():
        lines.append(f"        {kotlin_string(profile)} to")
        lines.append("            setOf(")
        lines.extend(f"                GroveIdentifierRole.{enum_name(role)}," for role in role_list)
        lines.append("            ),")
    lines.extend(
        [
            "    )",
            "",
            "    /** Exact DocumentReference profile mode to its required Grove identifier roles. */",
            "    public val activeDocumentProfileClaims: Map<Set<String>, Set<GroveIdentifierRole>> = mapOf(",
        ]
    )
    for profiles, role_list in claims["documentModes"]:
        lines.append("        setOf(")
        lines.extend(f"            {kotlin_string(profile)}," for profile in profiles)
        lines.append("        ) to setOf(")
        lines.extend(f"            GroveIdentifierRole.{enum_name(role)}," for role in role_list)
        lines.append("        ),")
    lines.extend(
        [
            "    )",
            "",
            "    /** Exact direct profile for every protocol-declared adapter-only active output type. */",
            "    public val adapterOnlyOutputProfiles: Map<String, String> = mapOf(",
        ]
    )
    for resource_type, profile in adapter_only_output_profiles(catalogs).items():
        lines.append(f"        {kotlin_string(resource_type)} to")
        lines.append(f"            {kotlin_string(profile)},")
    lines.extend(
        [
            "    )",
            "",
            "    /** Every Mobile or adapter profile admitted on the active lifecycle Provenance. */",
            *string_set("activeConversionProvenanceProfiles", claims["provenanceProfiles"]),
            "",
            "    /** Every adapter Observation profile that pairs with exactly one semantic profile. */",
            *string_set("adapterObservationProfiles", claims["adapterObservationProfiles"]),
            "",
            "    /** Every semantic Observation profile a Grove catalog publishes. */",
            "    public val semanticObservationProfiles: Set<String> = SEMANTIC_OBSERVATION_PROFILES",
            "",
            "    /** Observation profiles claimed alone, without a paired adapter profile. */",
            "    public val singleProfileObservationClaims: Set<String> = SINGLE_PROFILE_OBSERVATION_CLAIMS",
            "",
            "    /** The exact profile pair of a SensorKit hybrid Observation. */",
            *string_set("hybridObservationProfiles", claims["hybridObservationProfiles"]),
            "",
            "    /** Catalog-governed Reference paths and the resource types each may target. */",
            "    public val governedReferencePaths: List<GovernedReferencePath> = listOf(",
        ]
    )
    for row in protocol["referencePolicy"]["paths"]:
        targets = ", ".join(kotlin_string(target) for target in row["targetTypes"])
        repeating = "true" if row["repeating"] else "false"
        lines.append("        GovernedReferencePath(")
        lines.append(f'            resourceType = {kotlin_string(row["resourceType"])},')
        lines.append(f'            path = {kotlin_string(row["path"])},')
        lines.append(f"            repeating = {repeating},")
        lines.append(f"            targetTypes = setOf({targets}),")
        lines.append("        ),")
    lines.extend(
        [
            "    )",
            "",
            "    /** Catalog-governed Reference target types for extension-carried references. */",
            "    public val governedExtensionReferenceTargets: Map<String, Set<String>> = mapOf(",
        ]
    )
    for url, targets in extension_targets.items():
        rendered = ", ".join(kotlin_string(target) for target in targets)
        lines.append(f"        {kotlin_string(url)} to setOf({rendered}),")
    reserved = protocol["referencePolicy"]["identifierOnlyPatient"]["reservedSystems"]
    lines.extend(
        [
            "    )",
            "",
            "    /** Code-system URIs a logical Patient pseudonym may never be typed with. */",
            *string_set("reservedPatientIdentifierSystems", reserved),
            "",
            "    /** Adapter source-marker extension URLs to the adapter profiles that admit them. */",
            "    public val adapterSourceMarkers: Map<String, Set<String>> = ADAPTER_SOURCE_MARKERS",
            "",
            "    /** Every adapter conversion Provenance profile with the adapter outputs it must target. */",
            "    public val adapterConversionProvenanceClaims: List<AdapterConversionProvenanceClaim> =",
            "        ADAPTER_CONVERSION_PROVENANCE_CLAIMS",
            "",
            "    /** Every registered recording payload format, keyed by its format code. */",
            "    public val recordingFormats: Map<String, RecordingFormat> = RECORDING_FORMATS",
            "",
            "    /** Where the optional governed source identifier may and may never appear. */",
            "    public val governedSourceIdentifierPolicy: GovernedSourceIdentifierPolicy = GovernedSourceIdentifierPolicy(",
            f"        maxPerPrimaryOutput = {governed_policy['maxPerPrimaryOutput']},",
            f"        maxPrimaryOutputsPerEvent = {governed_policy['maxPrimaryOutputsPerEvent']},",
            "        neverResourceTypes = setOf(",
            *[f"            {kotlin_string(value)}," for value in governed_policy["neverResourceTypes"]],
            "        ),",
            "        neverProfiles = setOf(",
            *[f"            {kotlin_string(value)}," for value in governed_policy["neverProfiles"]],
            "        ),",
            "    )",
            "",
            "    /** Fixed Quantity system/code pairs keyed by every semantic profile that states one. */",
            "    public val quantitySemanticsByProfile: Map<String, QuantitySemantics> = QUANTITY_SEMANTICS_BY_PROFILE",
            "",
            "    /** Representational Quantity domains keyed by every semantic profile that states one. */",
            "    public val quantityValueDomainsByProfile: Map<String, QuantityValueDomain> =",
            "        QUANTITY_VALUE_DOMAINS_BY_PROFILE",
            "}",
            "",
            "/** Closed role vocabulary carried in Identifier.type from the Grove identifier-role CodeSystem. */",
            "public enum class GroveIdentifierRole(public val code: String, public val display: String) {",
        ]
    )
    for role, display in roles:
        lines.append(f"    {enum_name(role)}({kotlin_string(role)}, {kotlin_string(display)}),")
    lines.extend(
        [
            "    ;",
            "",
            "    public companion object {",
            "        /** The role a code names, or null when the code is not a Grove identifier role. */",
            "        public fun of(code: String): GroveIdentifierRole? = entries.firstOrNull { it.code == code }",
            "    }",
            "}",
            "",
            "/** Closed opaque identity kinds and their typed components from the exchange protocol. */",
            "public enum class OpaqueIdentityKind(",
            "    public val code: String,",
            "    public val identifierRole: GroveIdentifierRole,",
            "    public val components: List<String>,",
            ") {",
        ]
    )
    for kind in kinds:
        lines.append(f"    {enum_name(kind['kind'])}(")
        lines.append(f"        code = {kotlin_string(kind['kind'])},")
        lines.append(f"        identifierRole = GroveIdentifierRole.{enum_name(kind['identifierRole'])},")
        lines.append("        components = listOf(")
        lines.extend(f"            {kotlin_string(component)}," for component in kind["components"])
        lines.append("        ),")
        lines.append("    ),")
    lines.extend(
        [
            "    ;",
            "",
            "    /** How many typed components the kind's preimage carries. */",
            "    public val componentCount: Int",
            "        get() = components.size",
            "",
            "    public companion object {",
            "        /** The identity kind a code names, or null when the code is not an opaque identity kind. */",
            "        public fun of(code: String): OpaqueIdentityKind? = entries.firstOrNull { it.code == code }",
            "    }",
            "}",
            "",
            "/** Closed roles a prior graph node plays in a retraction target, with their Identifier role and types. */",
            "public enum class RetractionTargetRole(",
            "    public val code: String,",
            "    public val display: String,",
            "    public val identifierRole: GroveIdentifierRole,",
            "    public val resourceTypes: Set<ResourceType>,",
            ") {",
        ]
    )
    for role, rule in claims["retractionTargetRoles"].items():
        types = [f"ResourceType.{resource_type}" for resource_type in rule["resourceTypes"]]
        lines.append(f"    {enum_name(role)}(")
        lines.append(f"        code = {kotlin_string(role)},")
        lines.append(f"        display = {kotlin_string(target_displays[role])},")
        lines.append(f"        identifierRole = GroveIdentifierRole.{enum_name(rule['identifierRole'])},")
        inline = f"        resourceTypes = setOf({', '.join(types)}),"
        if len(inline) <= LINE_WIDTH:
            lines.append(inline)
        else:
            lines.append("        resourceTypes = setOf(")
            lines.extend(f"            {resource_type}," for resource_type in types)
            lines.append("        ),")
        lines.append("    ),")
    lines.extend(
        [
            "    ;",
            "",
            "    public companion object {",
            "        /** The target role a code names, or null when the code is not a retraction target role. */",
            "        public fun of(code: String): RetractionTargetRole? = entries.firstOrNull { it.code == code }",
            "    }",
            "}",
            "",
            "/** Entry-node roles of the study-context entries a producer bundles for a known enrollment. */",
            "public enum class StudyContextEntryNodeRole(public val code: String) {",
        ]
    )
    for role in study_roles:
        lines.append(f"    {enum_name(role)}({kotlin_string(role)}),")
    lines.extend(
        [
            "}",
            "",
            *string_set("SEMANTIC_OBSERVATION_PROFILES", claims["semanticObservationProfiles"], 0, "private "),
            "",
            *string_set("SINGLE_PROFILE_OBSERVATION_CLAIMS", claims["singleProfileObservationClaims"], 0, "private "),
            "",
            "private val QUANTITY_SEMANTICS_BY_PROFILE: Map<String, QuantitySemantics> = mapOf(",
        ]
    )
    for profile, (system, code) in quantity_semantics(catalogs).items():
        lines.append(f"    {kotlin_string(profile)} to")
        lines.append(f"        QuantitySemantics({kotlin_string(system)}, {kotlin_string(code)}),")
    lines.extend(
        [
            ")",
            "",
            "private val QUANTITY_VALUE_DOMAINS_BY_PROFILE: Map<String, QuantityValueDomain> = mapOf(",
        ]
    )
    for row in catalogs.measurements["measurements"]:
        domain = value_domain(row.get("quantity"))
        if domain is None:
            continue
        lines.append(f"    {kotlin_string(measurement_canonical(catalogs, row))} to")
        lines.append(f"        {render_value_domain(domain, 8)},")
    lines.extend([")", "", "private val ADAPTER_SOURCE_MARKERS: Map<String, Set<String>> = mapOf("])
    for url, profiles in adapter_source_markers(catalogs).items():
        lines.append(f"    {kotlin_string(url)} to setOf(")
        lines.extend(f"        {kotlin_string(profile)}," for profile in profiles)
        lines.append("    ),")
    lines.extend(
        [
            ")",
            "",
            "private val ADAPTER_CONVERSION_PROVENANCE_CLAIMS: List<AdapterConversionProvenanceClaim> = listOf(",
        ]
    )
    for row in adapter_conversion_provenance_claims(catalogs):
        lines.append("    AdapterConversionProvenanceClaim(")
        lines.append(f"        adapter = {kotlin_string(row['adapter'])},")
        lines.append(f"        profile = {kotlin_string(row['profile'])},")
        lines.append("        targetAdapterProfiles = setOf(")
        lines.extend(f"            {kotlin_string(profile)}," for profile in row["targetAdapterProfiles"])
        lines.append("        ),")
        lines.append("    ),")
    lines.extend([")", "", "private val RECORDING_FORMATS: Map<String, RecordingFormat> = mapOf("])
    for code, content_types in recording_formats(catalogs).items():
        lines.append(f"    {kotlin_string(code)} to RecordingFormat(")
        lines.append(f"        {kotlin_string(code)},")
        lines.append("        setOf(")
        lines.extend(f"            {kotlin_string(content_type)}," for content_type in content_types)
        lines.append("        ),")
        lines.append("    ),")
    lines.extend([")", ""])
    return HEADER + "\n".join(lines)


def generate_exchange_graph_rule(catalogs: Catalogs) -> str:
    rows = rule_rows(catalogs)
    lines = [
        f"package {CONTRACT_PACKAGE}",
        "",
        "/** Every registered producer diagnostic, with the registry reason and severity it carries. */",
        "public enum class ExchangeGraphRule(",
        "    public val code: String,",
        "    public val reason: String,",
        "    public val severity: ProducerDiagnostic.Severity,",
        ") {",
    ]
    for row in rows:
        severity = row.get("severity", "error").upper()
        lines.append(f"    {enum_name(row['code'])}(")
        lines.append(f"        code = {kotlin_string(row['code'])},")
        lines.append(f"        reason = {wrapped_string(row['reason'], 12)},")
        lines.append(f"        severity = ProducerDiagnostic.Severity.{severity},")
        lines.append("    ),")
    lines.extend(
        [
            "    ;",
            "",
            "    public companion object {",
            "        /** The rule a registry code names, or null when the registry does not know the code. */",
            "        public fun of(code: String): ExchangeGraphRule? = entries.firstOrNull { it.code == code }",
            "    }",
            "}",
            "",
        ]
    )
    return HEADER + "\n".join(lines)


# --- Generated adapter sources ------------------------------------------------------------------


def health_connect_outputs(catalogs: Catalogs) -> list[str]:
    return sorted(
        {
            output["measurement"]
            for record in catalogs.health_connect["recordTypes"]
            for output in record.get("outputs", [])
        }
    )


def produced_measurement(catalogs: Catalogs, identifier: str) -> dict[str, Any]:
    adapter = {row["id"]: row for row in catalogs.health_connect["adapterMeasurements"]}
    measurements = {row["id"]: row for row in catalogs.measurements["measurements"]}
    row = adapter.get(identifier, measurements.get(identifier))
    if row is None:
        raise SystemExit(f"{identifier}: the Health Connect adapter emits an output no catalog defines")
    return row


def measurement_profile(catalogs: Catalogs, row: dict[str, Any]) -> str:
    profile = row["profile"]
    if profile.startswith("https://"):
        return profile
    return measurement_canonical(catalogs, row)


def generate_health_connect_contract(catalogs: Catalogs) -> str:
    produced = health_connect_outputs(catalogs)
    adapter_measurements = {row["id"]: row for row in catalogs.health_connect["adapterMeasurements"]}
    shared: list[tuple[str, str]] = []
    dietary: list[tuple[str, str]] = []
    adapter_specific: list[tuple[str, str]] = []
    for identifier in produced:
        row = produced_measurement(catalogs, identifier)
        if identifier in adapter_measurements:
            canonical = row["profile"]
            expected = f"{HEALTH_CONNECT_CANONICAL}/StructureDefinition/"
            if not canonical.startswith(expected):
                raise SystemExit(f"{identifier}: {canonical} is not published by this adapter")
            adapter_specific.append((constant_name(canonical[len(expected):], "_PROFILE"), canonical[len(expected):]))
            continue
        owner = row.get("owner", "mobile")
        if owner not in ("mobile", "health-connect"):
            raise SystemExit(f"{identifier}: owner {owner!r} publishes outside the packages this adapter names")
        if owner == "mobile" and identifier.startswith("dietary-"):
            dietary.append((identifier, row["profile"]))
            continue
        target = adapter_specific if owner == "health-connect" else shared
        target.append((constant_name(row["profile"], "_PROFILE"), row["profile"]))
    writer_application = catalogs.health_connect["dataOriginApplication"]
    expected_writer = {
        "sourceField": "Metadata.dataOrigin.packageName",
        "r4Element": "Provenance.entity.agent.who",
        "referenceType": "Device",
        "referenceMode": "identifier-only",
        "literalReferenceAllowed": False,
        "eventBundleEntryRequired": False,
        "profileClaimRequired": False,
    }
    if any(writer_application.get(key) != value for key, value in expected_writer.items()):
        raise SystemExit("The Health Connect writer is no longer the admitted identifier-only Device reference")
    provenance_profile = next(
        claim["profile"]
        for claim in catalogs.claims["adapterConversionProvenanceClaims"]
        if claim["adapter"] == "health-connect"
    )
    specimen_profile = catalogs.claims["healthConnectSpecimenClaim"]["profile"]
    observation_profile = next(
        profile
        for profile in catalogs.claims["observationAdapterClaim"]["adapterProfiles"]
        if profile.startswith(HEALTH_CONNECT_CANONICAL)
    )
    source = catalogs.health_connect["source"]
    writer = catalogs.health_connect["identity"]["writerRecord"]["revision"]
    mobile_systems = fsh_code_systems(catalogs.repository / "mobile")
    health_connect_systems = fsh_code_systems(catalogs.repository / "health-connect")

    lines: list[str] = [
        f"package {ADAPTER_PACKAGE}",
        "",
        "import org.grovealliance.fhir.ExchangeContract",
        "",
        "/** Canonicals the Health Connect adapter emits, projected from the grove-fhir catalogs. */",
        "public object HealthConnectContract {",
        declaration("HEALTH_CONNECT_BASE", '"${ExchangeContract.CANONICAL_ROOT}/health-connect"'),
        declaration("MOBILE_BASE", "ExchangeContract.MOBILE_BASE"),
        declaration(
            "SOURCE_PACKAGE",
            kotlin_string(source["package"]),
            "The AndroidX artifact whose Record inventory this adapter converts.",
        ),
        declaration("SOURCE_VERSION", kotlin_string(source["version"])),
        declaration("RECORD_TYPE_COUNT", str(source["recordTypeCount"])),
        declaration(
            "ADAPTER_ID",
            kotlin_string(catalogs.health_connect["identity"]["adapterId"]),
            "The adapter-id component of every Health Connect opaque identity.",
        ),
        declaration(
            "WRITER_RECORD_VERSION_MAXIMUM",
            f"{writer['versionMaximum']}L",
            "The largest writer record version the contract admits.",
        ),
        "",
        declaration("HEALTH_CONNECT_OBSERVATION_PROFILE", kotlin_string(observation_profile)),
        declaration("HEALTH_CONNECT_SPECIMEN_PROFILE", kotlin_string(specimen_profile)),
        declaration("HEALTH_CONNECT_PROVENANCE_PROFILE", kotlin_string(provenance_profile)),
        "",
    ]
    for name, profile in shared:
        lines.append(declaration(name, f'"$MOBILE_BASE/StructureDefinition/{profile}"'))
    lines.append("")
    for name, profile in adapter_specific:
        lines.append(declaration(name, f'"$HEALTH_CONNECT_BASE/StructureDefinition/{profile}"'))
    lines.extend(
        [
            "",
            "    /** Every dietary nutrient the adapter emits, keyed by its catalog measurement id. */",
            "    public val mobileDietaryProfiles: Map<String, String> = mapOf(",
        ]
    )
    for identifier, profile in dietary:
        lines.append(f'        "{identifier}" to "$MOBILE_BASE/StructureDefinition/{profile}",')
    lines.extend(
        [
            "    )",
            "",
            "    /** Profiles the shared Mobile package owns, which this adapter also claims. */",
            "    public val sharedMeasurementProfiles: Set<String> = setOf(",
            *[f"        {name}," for name, _ in shared],
            "    ) + mobileDietaryProfiles.values",
            "",
            "    /** Profiles only this adapter publishes. */",
            "    public val adapterSpecificObservationProfiles: Set<String> = setOf(",
            *[f"        {name}," for name, _ in adapter_specific],
            "    )",
            declaration(
                "WRITER_PACKAGE_SYSTEM",
                kotlin_string(writer_application["identifierSystem"]),
                "The Identifier.system of the Android package name that names the writer of a record.",
            ),
            declaration("RECORDING_METHOD_EXTENSION", '"$MOBILE_BASE/StructureDefinition/grove-recording-method"'),
            declaration(
                "HEALTH_CONNECT_SESSION_TITLE",
                kotlin_string(catalogs.health_connect["contextMappings"]["sessionTitle"]["extension"]),
            ),
            declaration(
                "HEALTH_CONNECT_GLUCOSE_MEAL_CONTEXT",
                kotlin_string(catalogs.health_connect["contextMappings"]["bloodGlucoseMealContext"]["extension"]),
            ),
            declaration(
                "HEALTH_CONNECT_RECORD_TYPE_EXTENSION",
                kotlin_string(catalogs.health_connect["sourceTypeExtension"]["url"]),
            ),
            "",
        ]
    )
    for identifier in mobile_systems:
        name = constant_name(identifier, prefix="GROVE", strip=r"^grove-")
        if name == "GROVE_RETRACTION_TARGET_ROLE":
            continue
        lines.append(declaration(name, f'"$MOBILE_BASE/CodeSystem/{identifier}"'))
    for identifier in health_connect_systems:
        lines.append(declaration(constant_name(identifier), f'"$HEALTH_CONNECT_BASE/CodeSystem/{identifier}"'))
    lines.append("")
    for name, value, doc in EXTERNAL_SYSTEMS:
        lines.append(declaration(name, kotlin_string(value), doc))
    lines.extend(["}", ""])
    return HEADER + "\n".join(lines)


def output_role(catalogs: Catalogs, output: dict[str, Any]) -> tuple[str, str, str | None]:
    """The output role token, retraction role and graph rule of one catalog output."""
    rules = catalogs.health_connect["identity"]["sourceOutput"]["outputDiscriminatorRules"]
    count_rule = output["countRule"]
    if count_rule == "graph-specific":
        graph_rule = catalogs.health_connect["graphRules"][output["graphRule"]]
        structured = [item for item in graph_rule["outputs"] if item["resourceRole"] != "synthesized-specimen"]
        if len(structured) != 1:
            raise SystemExit(f"{output['graphRule']}: expected one structured graph output")
        child = structured[0]["resourceRole"] == "workout-child"
        return structured[0]["outputRole"], "child-output" if child else "primary-output", output["graphRule"]
    if count_rule not in rules:
        raise SystemExit(f"{count_rule}: no output discriminator rule")
    role = rules[count_rule].split(";", 1)[0].removeprefix("output-role ").strip()
    child = count_rule == "one-per-stage"
    return role, "child-output" if child else "primary-output", None


def generate_health_connect_source_type(catalogs: Catalogs) -> str:
    records = catalogs.health_connect["recordTypes"]
    statuses = catalogs.health_connect["statusVocabulary"]
    count_rules = catalogs.health_connect["outputCountRules"]
    if len(records) != catalogs.health_connect["source"]["recordTypeCount"]:
        raise SystemExit("The Health Connect record inventory count no longer matches its rows")
    tokens = [record["token"] for record in records]
    if len(set(tokens)) != len(tokens) or any(not token.endswith("Record") for token in tokens):
        raise SystemExit("Health Connect record tokens must be unique AndroidX Record class names")
    lines: list[str] = [
        "@file:OptIn(androidx.health.connect.client.feature.ExperimentalMindfulnessSessionApi::class)",
        "",
        f"package {ADAPTER_PACKAGE}",
        "",
        "import androidx.health.connect.client.records.Record",
        "import org.grovealliance.fhir.RetractionTargetRole",
        "import org.hl7.fhir.r4.model.ResourceType",
        "import kotlin.reflect.KClass",
        "",
        "/** How the adapter catalog classifies one AndroidX Record class. */",
        "public enum class HealthConnectSourceStatus(public val code: String) {",
    ]
    for status in statuses:
        lines.append(f"    {enum_name(status)}({kotlin_string(status)}),")
    lines.extend(
        [
            "}",
            "",
            "/** The closed output-count rules of the adapter catalog. */",
            "public enum class HealthConnectOutputCountRule(public val code: String) {",
        ]
    )
    for rule in count_rules:
        lines.append(f"    {enum_name(rule)}({kotlin_string(rule)}),")
    lines.extend(
        [
            "}",
            "",
            "/** Every AndroidX Health Connect Record class the adapter catalog inventories. */",
            "public enum class HealthConnectSourceType(",
            "    public val token: String,",
            "    public val recordClass: KClass<out Record>,",
            "    public val status: HealthConnectSourceStatus,",
            ") {",
        ]
    )
    for record in records:
        lines.append(
            f"    {enum_name(record['token'].removesuffix('Record'))}(\n"
            f"        token = {kotlin_string(record['token'])},\n"
            f"        recordClass = androidx.health.connect.client.records.{record['token']}::class,\n"
            f"        status = HealthConnectSourceStatus.{enum_name(record['status'])},\n"
            "    ),"
        )
    lines.extend(
        [
            "    ;",
            "",
            "    public companion object {",
            "        private val byClass: Map<KClass<out Record>, HealthConnectSourceType> =",
            "            entries.associateBy { it.recordClass }",
            "",
            "        /** The catalog source type of a record, or null for a Record class outside the inventory. */",
            "        public fun of(record: Record): HealthConnectSourceType? = byClass[record::class]",
            "",
            "        /** The catalog source type a token names, or null when the inventory has no such token. */",
            "        public fun of(token: String): HealthConnectSourceType? = entries.firstOrNull { it.token == token }",
            "    }",
            "}",
            "",
            "/** The adapter catalog rows, keyed by source type. */",
            "public object HealthConnectCatalog {",
            "    /** Every inventoried source type with its status, outputs and admitted contexts. */",
            "    public val entries: Map<HealthConnectSourceType, HealthConnectCatalogEntry> =",
            "        CATALOG_ENTRIES.associateBy { it.type }",
            "",
            "    /** The catalog row of one source type. */",
            "    public operator fun get(type: HealthConnectSourceType): HealthConnectCatalogEntry = entries.getValue(type)",
            "",
            "    /** Every output the catalog admits for one source type. */",
            "    public fun outputs(type: HealthConnectSourceType): List<HealthConnectOutput> = get(type).outputs",
            "",
            "    /** Every public source field of every supported type with its reviewed disposition. */",
            "    public val fieldDispositions: Map<HealthConnectSourceType, Map<String, HealthConnectFieldDisposition>>",
            "        get() = HealthConnectFieldDispositions.records",
            "}",
            "",
            "private val CATALOG_ENTRIES: List<HealthConnectCatalogEntry> = listOf(",
        ]
    )
    for record in records:
        source_type = enum_name(record["token"].removesuffix("Record"))
        contexts = ", ".join(kotlin_string(context) for context in record.get("context", []))
        reason = record.get("reason")
        lines.append("    HealthConnectCatalogEntry(")
        lines.append(f"        type = HealthConnectSourceType.{source_type},")
        lines.append(f"        status = HealthConnectSourceStatus.{enum_name(record['status'])},")
        lines.append(f"        contexts = setOf({contexts}),")
        lines.append(f"        reason = {wrapped_string(reason, 12) if reason else 'null'},")
        outputs = record.get("outputs", [])
        if not outputs:
            lines.append("        outputs = emptyList(),")
        else:
            lines.append("        outputs = listOf(")
            specimen_rendered = False
            for item in outputs:
                role, retraction_role, graph_rule = output_role(catalogs, item)
                arguments = [
                    f"measurement = {kotlin_string(item['measurement'])}",
                    "resourceType = ResourceType.Observation",
                    f"countRule = HealthConnectOutputCountRule.{enum_name(item['countRule'])}",
                    f"outputRole = {kotlin_string(role)}",
                    f"retractionRole = RetractionTargetRole.{enum_name(retraction_role)}",
                    f"graphRule = {kotlin_string(graph_rule) if graph_rule else 'null'}",
                    f"condition = {kotlin_string(item['when']) if item.get('when') else 'null'}",
                ]
                lines.append("            HealthConnectOutput(")
                lines.extend(f"                {argument}," for argument in arguments)
                lines.append("            ),")
                if graph_rule is None or specimen_rendered:
                    continue
                specimen = [
                    entry
                    for entry in catalogs.health_connect["graphRules"][graph_rule]["outputs"]
                    if entry["resourceRole"] == "synthesized-specimen"
                ]
                if specimen:
                    specimen_rendered = True
                    lines.append("            HealthConnectOutput(")
                    lines.append("                measurement = null,")
                    lines.append("                resourceType = ResourceType.Specimen,")
                    lines.append("                countRule = HealthConnectOutputCountRule.GRAPH_SPECIFIC,")
                    lines.append(f"                outputRole = {kotlin_string(specimen[0]['outputRole'])},")
                    lines.append("                retractionRole = RetractionTargetRole.SPECIMEN,")
                    lines.append(f"                graphRule = {kotlin_string(graph_rule)},")
                    lines.append("                condition = null,")
                    lines.append("            ),")
            lines.append("        ),")
        lines.append("    ),")
    lines.extend([")", ""])
    return HEADER + "\n".join(lines)


def generate_health_connect_measurements(catalogs: Catalogs) -> str:
    produced = health_connect_outputs(catalogs)
    adapter_measurements = {row["id"]: row for row in catalogs.health_connect["adapterMeasurements"]}
    lines: list[str] = [
        f"package {ADAPTER_PACKAGE}",
        "",
        "import org.grovealliance.fhir.QuantityValueDomain",
        "",
        "/** Every measurement the Health Connect adapter emits, keyed by its catalog id. */",
        "internal object HealthConnectMeasurements {",
        "    val byId: Map<String, MeasurementSpec> = MEASUREMENTS.associateBy { it.id }",
        "",
        "    /** The output measurements the catalog admits, keyed by the profile each claims. */",
        "    val byProfile: Map<String, MeasurementSpec> = HealthConnectCatalog.entries.values",
        "        .flatMap { it.outputs }",
        "        .mapNotNull { it.measurement }",
        "        .toSet()",
        "        .associate { byId.getValue(it).profile to byId.getValue(it) }",
        "",
        "    fun spec(id: String): MeasurementSpec = byId.getValue(id)",
        "}",
        "",
        "private val MEASUREMENTS: List<MeasurementSpec> = listOf(",
    ]
    for identifier in produced:
        row = produced_measurement(catalogs, identifier)
        adapter_specific = identifier in adapter_measurements or row.get("owner") == "health-connect"
        category = row.get("category")
        quantity = row.get("quantity")
        components = row.get("components") or []
        required = row.get("requiredCodings") or []
        effective = row.get("effective")
        if effective not in EFFECTIVE_SHAPES:
            raise SystemExit(f"{identifier}: unknown effective shape {effective!r}")
        value_kind = row.get("valueKind") or ("quantity" if quantity else "codeableConcept")
        if value_kind not in ("quantity", "codeableConcept", "components"):
            raise SystemExit(f"{identifier}: unknown value kind {value_kind!r}")
        lines.append("    MeasurementSpec(")
        lines.append(f"        id = {kotlin_string(identifier)},")
        lines.append(f"        profile = {kotlin_string(measurement_profile(catalogs, row))},")
        lines.append(f"        adapterSpecific = {str(adapter_specific).lower()},")
        lines.append(f"        code = {render_coding(row['code'], 8)},")
        if required:
            lines.append("        requiredCodings = listOf(")
            lines.extend(f"            {render_coding(coding, 12)}," for coding in required)
            lines.append("        ),")
        else:
            lines.append("        requiredCodings = emptyList(),")
        lines.append(f"        category = {render_coding(category, 8) if category else 'null'},")
        lines.append(f"        valueKind = MeasurementValueKind.{enum_name(value_kind)},")
        if quantity:
            domain = value_domain(quantity)
            lines.append("        quantity = QuantitySpec(")
            lines.append(f"            system = {kotlin_string(quantity['system'])},")
            lines.append(f"            code = {kotlin_string(quantity['code'])},")
            lines.append(f"            unit = {kotlin_string(quantity['unit'])},")
            lines.append(f"            domain = {render_value_domain(domain, 12) if domain else 'null'},")
            lines.append("        ),")
        else:
            lines.append("        quantity = null,")
        result_system = row.get("resultCodeSystem")
        lines.append(f"        resultCodeSystem = {kotlin_string(result_system) if result_system else 'null'},")
        if components:
            lines.append("        components = listOf(")
            for component in components:
                component_quantity = component.get("quantity")
                coding = {"system": component["system"], "code": component["code"], "display": component.get("display")}
                lines.append("            ComponentSpec(")
                lines.append(f"                id = {kotlin_string(component['id'])},")
                lines.append(f"                code = {render_coding(coding, 16)},")
                if component_quantity:
                    lines.append("                quantity = QuantitySpec(")
                    lines.append(f"                    system = {kotlin_string(component_quantity['system'])},")
                    lines.append(f"                    code = {kotlin_string(component_quantity['code'])},")
                    lines.append(f"                    unit = {kotlin_string(component_quantity['unit'])},")
                    lines.append("                    domain = null,")
                    lines.append("                ),")
                else:
                    lines.append("                quantity = null,")
                lines.append("            ),")
            lines.append("        ),")
        else:
            lines.append("        components = emptyList(),")
        lines.append(f"        effective = EffectiveShape.{EFFECTIVE_SHAPES[effective]},")
        lines.append("    ),")
    lines.extend([")", ""])
    return HEADER + "\n".join(lines)


def generate_health_connect_context_mappings(catalogs: Catalogs) -> str:
    mappings = catalogs.health_connect["contextMappings"]
    mobile_systems = fsh_code_systems(catalogs.repository / "mobile")
    health_connect_systems = fsh_code_systems(catalogs.repository / "health-connect")
    members: list[str] = []
    tables: list[str] = []

    def table(name: str, kotlin_type: str, body: list[str]) -> None:
        constant = f"HEALTH_CONNECT_{enum_name(name)}"
        members.append(f"    val {name}: {kotlin_type} = {constant}")
        members.append("")
        tables.append(f"private val {constant}: {kotlin_type} = {body[0]}")
        tables.extend(body[1:])
        tables.append("")

    def shared_coded(name: str) -> None:
        mapping = mappings[name]
        body = [
            "SourceCodedMapping(",
            f"    sourceSystem = {kotlin_string(mapping['sourceCodeSystem'])},",
            f"    appliesToMeasurement = {kotlin_string(mapping['appliesToMeasurement'])},",
            "    values = listOf(",
        ]
        for value in mapping["values"]:
            body.append("        SourceCodedValue(")
            body.append(f"            source = {kotlin_string(value['source'])},")
            body.append(f"            code = {kotlin_string(value['code'])},")
            body.append(f"            display = {kotlin_string(value['display'])},")
            body.append(f"            shared = {kotlin_string(value['shared'])},")
            body.append("        ),")
        body.extend(["    ),", ")"])
        table(name, "SourceCodedMapping", body)

    for name in (
        "sleepStage",
        "menstruationFlow",
        "ovulationTestResult",
        "sexualActivityProtection",
        "cervicalMucusAppearance",
        "cervicalMucusSensation",
    ):
        shared_coded(name)

    def source_only(name: str, code_system: str, values: list[dict[str, Any]]) -> None:
        body = ["SourceOnlyMapping(", f"    codeSystem = {kotlin_string(code_system)},", "    values = listOf("]
        for value in values:
            coding = value.get("coding", value)
            if coding is None:
                continue
            body.append("        SourceOnlyValue(")
            body.append(f"            source = {kotlin_string(value['source'])},")
            body.append(f"            code = {kotlin_string(coding['code'])},")
            body.append(f"            display = {kotlin_string(coding['display'])},")
            body.append("        ),")
        body.extend(["    ),", ")"])
        table(name, "SourceOnlyMapping", body)

    for name in ("mindfulnessSessionType", "vo2MaxMeasurementMethod"):
        source_only(name, mappings[name]["codeSystem"], mappings[name]["values"])
    meal = mappings["bloodGlucoseMealContext"]
    for field in ("relationToMeal", "mealType"):
        source_only(field, meal[field]["codeSystem"], meal[field]["values"])

    def external_coded(name: str) -> None:
        body = ["ExternalCodedMapping(", "    values = listOf("]
        for value in mappings[name]["values"]:
            coding = value.get("coding")
            body.append("        ExternalCodedValue(")
            body.append(f"            source = {kotlin_string(value['source'])},")
            body.append(f"            coding = {render_coding(coding, 12) if coding else 'null'},")
            body.append("        ),")
        body.extend(["    ),", ")"])
        table(name, "ExternalCodedMapping", body)

    for name in (
        "bloodPressureBodyPosition",
        "bloodPressureMeasurementLocation",
        "temperatureMeasurementLocation",
        "skinTemperatureMeasurementLocation",
    ):
        external_coded(name)

    body = ["listOf("]
    for value in mappings["bloodGlucoseSpecimen"]["values"]:
        coding = value.get("coding")
        measurement = value.get("measurement")
        body.append("    SpecimenSourceValue(")
        body.append(f"        source = {kotlin_string(value['source'])},")
        body.append(f"        status = HealthConnectSourceStatus.{enum_name(value['status'])},")
        body.append(f"        measurement = {kotlin_string(measurement) if measurement else 'null'},")
        body.append(f"        specimenType = {render_coding(coding, 8) if coding else 'null'},")
        body.append("    ),")
    body.append(")")
    table("bloodGlucoseSpecimen", "List<SpecimenSourceValue>", body)

    for name in ("exerciseType", "exerciseSegmentType"):
        mapping = mappings[name]
        body = [
            "AllowedSourceCodes(",
            f"    sourceSystem = {kotlin_string(mapping['sourceCodeSystem'])},",
            f"    appliesToMeasurement = {kotlin_string(mapping['appliesToMeasurement'])},",
            "    codes = setOf(",
        ]
        body.extend(f"        {kotlin_string(code)}," for code in mapping["allowedSourceCodes"])
        body.extend(["    ),", ")"])
        table(name, "AllowedSourceCodes", body)

    lines: list[str] = [
        f"package {ADAPTER_PACKAGE}",
        "",
        "/** Every Health Connect context mapping, keyed by the exact AndroidX source token. */",
        "internal object HealthConnectContextMappings {",
        *members,
        "    /** Display strings of every Grove CodeSystem concept, by system and code. */",
        "    val displays: Map<String, Map<String, String>> = CONCEPT_DISPLAYS",
        "}",
        "",
        *tables,
        "private val CONCEPT_DISPLAYS: Map<String, Map<String, String>> = mapOf(",
    ]
    for base, systems in ((MOBILE_CANONICAL, mobile_systems), (HEALTH_CONNECT_CANONICAL, health_connect_systems)):
        for identifier, concepts in systems.items():
            if not concepts:
                continue
            lines.append(f"    {kotlin_string(f'{base}/CodeSystem/{identifier}')} to mapOf(")
            lines.extend(f"        {kotlin_string(code)} to {kotlin_string(display)}," for code, display in concepts)
            lines.append("    ),")
    lines.extend([")", ""])
    return HEADER + "\n".join(lines)



def generate_test_vectors(catalogs: Catalogs) -> str:
    kinds = catalogs.protocol["opaqueIdentity"]["identityKinds"]
    vectors = catalogs.protocol["testVectors"]
    kind_names = [row["kind"] for row in kinds]
    identities = vectors.get("identities")
    invalid = vectors.get("invalidIdentities")
    systems = vectors.get("identitySystems")
    vector_kinds = [row["identityKind"] for row in identities] if isinstance(identities, list) else []
    if (
        set(vector_kinds) != set(kind_names)
        or not isinstance(invalid, list)
        or len(invalid) != 6
        or not isinstance(systems, list)
        or [row["identityKind"] for row in systems] != kind_names
    ):
        raise SystemExit(
            "The normative test vectors must cover every closed identity kind, retain all six invalid "
            "identity vectors and state one identifier system per kind"
        )
    return json.dumps(vectors, ensure_ascii=False, indent=2) + "\n"


def equality_fixtures(catalogs: Catalogs) -> dict[str, str]:
    corpus = catalogs.repository / "Conformance" / "corpora" / "receiver-lifecycle"
    events = json.loads((corpus / "events.json").read_text(encoding="utf-8"))
    sequences = json.loads((corpus / "sequences.json").read_text(encoding="utf-8"))
    selected = [sequence for sequence in sequences["sequences"] if sequence["id"] in EQUALITY_SEQUENCES]
    if [sequence["id"] for sequence in selected] != list(EQUALITY_SEQUENCES):
        raise SystemExit("The receiver-lifecycle corpus must carry the reformatted-replay and lexeme-replay sequences")
    aliases: list[str] = []
    for sequence in selected:
        for step in sequence["steps"]:
            if step["event"] not in aliases:
                aliases.append(step["event"])
    index = {
        "schemaVersion": 0,
        "contractLock": events["contractLock"],
        "equality": catalogs.protocol["payload"]["equality"],
        "events": {alias: events["events"][alias] for alias in aliases},
        "sequences": selected,
    }
    files = {"receiver-lifecycle/equality.json": json.dumps(index, ensure_ascii=False, indent=2) + "\n"}
    for alias in aliases:
        path = events["events"][alias]["path"]
        files[f"receiver-lifecycle/{path}"] = (corpus / path).read_text(encoding="utf-8")
    return files


# --- Entry point --------------------------------------------------------------------------------


def outputs(catalogs: Catalogs, root: Path) -> dict[Path, str]:
    vectors = generate_test_vectors(catalogs)
    vectors_license = LICENSE_SIDECAR.format(source="exchange-protocol catalog")
    result = {
        root / CONTRACT_SOURCES / "ExchangeContract.kt": generate_exchange_contract(catalogs),
        root / CONTRACT_SOURCES / "ExchangeGraphRule.kt": generate_exchange_graph_rule(catalogs),
        root / CONTRACT_TEST_RESOURCES / "grove-exchange-protocol-test-vectors.json": vectors,
        root / CONTRACT_TEST_RESOURCES / "grove-exchange-protocol-test-vectors.json.license": vectors_license,
        root / ADAPTER_SOURCES / "HealthConnectContract.kt": generate_health_connect_contract(catalogs),
        root / ADAPTER_SOURCES / "HealthConnectSourceType.kt": generate_health_connect_source_type(catalogs),
        root / ADAPTER_SOURCES / "HealthConnectMeasurements.kt": generate_health_connect_measurements(catalogs),
        root / ADAPTER_SOURCES / "HealthConnectContextMappings.kt": generate_health_connect_context_mappings(catalogs),
        root / ADAPTER_TEST_RESOURCES / "grove-exchange-protocol-test-vectors.json": vectors,
        root / ADAPTER_TEST_RESOURCES / "grove-exchange-protocol-test-vectors.json.license": vectors_license,
    }
    for name, content in equality_fixtures(catalogs).items():
        result[root / CONTRACT_TEST_RESOURCES / name] = content
        result[root / CONTRACT_TEST_RESOURCES / f"{name}.license"] = LICENSE_SIDECAR.format(source="receiver-lifecycle corpus")
    return result


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog-directory", type=Path, required=True)
    parser.add_argument("--repository-root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    catalogs = Catalogs(arguments.catalog_directory.resolve())
    generated = outputs(catalogs, arguments.repository_root.resolve())
    if arguments.check:
        stale = False
        for path, content in generated.items():
            actual = path.read_text(encoding="utf-8") if path.exists() else ""
            if actual != content:
                print(f"error: {path} is not synchronized with the grove-fhir catalogs", file=sys.stderr)
                stale = True
        return int(stale)
    for path, content in generated.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
