#!/usr/bin/env python3
"""Project the Grove FHIR catalogs onto the Kotlin canonical contract.

The Swift and TypeScript contracts have always been generated from the catalogs; this one was
hand-written, so it could fall behind without anything failing. Generating it closes the last
place where a catalog change reaches two languages and silently misses the third.
"""

# This source file belongs to the My Heart Counts Android project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any


HEADER = """//
// This source file belongs to the My Heart Counts Android project
//
// SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
//
// SPDX-License-Identifier: MIT

// Generated by Scripts/generate-grove-fhir-kotlin-contract.py. Do not edit by hand.

package org.grovealliance.health.fhir

"""

# Canonicals the contract needs that no catalog owns, because they belong to HL7 or a
# terminology authority rather than to Grove.
EXTERNAL_SYSTEMS: list[tuple[str, str, str]] = [
    ("OBSERVATION_BODY_POSITION", "http://hl7.org/fhir/StructureDefinition/observation-bodyPosition", ""),
    ("LOINC", "http://loinc.org", ""),
    ("SNOMED_CT", "http://snomed.info/sct", ""),
    ("UCUM", "http://unitsofmeasure.org", ""),
    ("MDC", "urn:iso:std:iso:11073:10101", ""),
    ("APPLICATION_SOFTWARE_VERSION", "531975", "The ISO 11073 MDC software-revision code."),
    ("OBSERVATION_CATEGORY", "http://terminology.hl7.org/CodeSystem/observation-category", ""),
    ("RECORD_LIFECYCLE", "http://terminology.hl7.org/CodeSystem/iso-21089-lifecycle", ""),
    ("PROVENANCE_PARTICIPANT", "http://terminology.hl7.org/CodeSystem/provenance-participant-type", ""),
    ("RESEARCH_STUDY_EXTENSION", "http://hl7.org/fhir/StructureDefinition/workflow-researchStudy", ""),
]

HEALTH_CONNECT_CANONICAL = "https://grovealliance.org/fhir/health-connect"
MOBILE_BASE = "$MOBILE_BASE"
HEALTH_CONNECT_BASE = "$HEALTH_CONNECT_BASE"


def load(catalog_directory: Path, name: str) -> dict[str, Any]:
    return json.loads((catalog_directory / name).read_text(encoding="utf-8"))


def constant_name(
    identifier: str, suffix: str = "", prefix: str | None = None, strip: str | None = None
) -> str:
    """`grove-mobile-heart-rate` becomes `MOBILE_HEART_RATE_PROFILE`.

    Profiles carry the package prefix a reader expects; the shared code systems keep the `GROVE_`
    names the converter already uses, so generating this file changes no call site.
    """
    stem = re.sub(strip or r"^(grove-mobile-|grove-|health-connect-)", "", identifier)
    if prefix is None:
        prefix = "MOBILE" if identifier.startswith(("grove-mobile-", "grove-")) else "HEALTH_CONNECT"
    body = re.sub(r"[^A-Za-z0-9]+", "_", stem).strip("_").upper()
    return f"{prefix}_{body}{suffix}"


def declaration(name: str, value: str, doc: str = "") -> str:
    line = f'    const val {name} = {value}'
    # ktlint wants a blank line before a documented declaration.
    prefix = f"\n    /** {doc} */\n" if doc else ""
    if len(line) <= 120:
        return prefix + line
    return prefix + f"    const val {name} =\n        {value}"


def profile_value(base: str, identifier: str) -> str:
    return f'"{base}/StructureDefinition/{identifier}"'


def system_value(base: str, kind: str, identifier: str) -> str:
    return f'"{base}/{kind}/{identifier}"'


def health_connect_outputs(catalogs: dict[str, Any]) -> list[str]:
    """Every measurement the Health Connect adapter admits an output for."""
    return sorted(
        {
            output["measurement"]
            for record in catalogs["health-connect"]["recordTypes"]
            for output in record.get("outputs", [])
        }
    )


def generate(catalog_directory: Path) -> str:
    catalogs = {
        "measurements": load(catalog_directory, "measurement-catalog.json"),
        "health-connect": load(catalog_directory, "health-connect-adapter.json"),
        "graph": load(catalog_directory, "package-graph.json"),
    }
    measurements = {m["id"]: m for m in catalogs["measurements"]["measurements"]}
    adapter_measurements = {m["id"]: m for m in catalogs["health-connect"]["adapterMeasurements"]}
    produced = health_connect_outputs(catalogs)

    shared: list[tuple[str, str]] = []
    dietary: list[tuple[str, str]] = []
    adapter_specific: list[tuple[str, str]] = []
    for identifier in produced:
        if identifier in adapter_measurements:
            canonical = adapter_measurements[identifier]["profile"]
            expected = f"{HEALTH_CONNECT_CANONICAL}/StructureDefinition/"
            if not canonical.startswith(expected):
                raise SystemExit(
                    f"{identifier}: {canonical} is not published by this adapter; the contract "
                    "cannot state it under the Health Connect base"
                )
            profile = canonical[len(expected):]
            adapter_specific.append((constant_name(profile, "_PROFILE"), profile))
            continue
        measurement = measurements[identifier]
        profile = measurement["profile"]
        owner = measurement.get("owner", "mobile")
        if owner not in ("mobile", "health-connect"):
            raise SystemExit(
                f"{identifier}: owner {owner!r} publishes outside the packages this contract names"
            )
        target = adapter_specific if owner == "health-connect" else shared
        if owner == "mobile" and identifier.startswith("dietary-"):
            dietary.append((identifier, profile))
            continue
        target.append((constant_name(profile, "_PROFILE"), profile))

    lines: list[str] = [
        "/** Canonicals shared with the Grove FHIR Mobile and Health Connect packages. */",
        "object HealthConnectContract {",
        declaration("FHIR_VERSION", f'"{catalogs["measurements"]["fhirVersion"]}"'),
        declaration("PACKAGE_VERSION", f'"{catalogs["measurements"]["version"]}"'),
        declaration(
            "CONVERSION_CONTRACT_VERSION",
            f'"health-connect-r4-{catalogs["measurements"]["version"]}"',
        ),
        declaration("CANONICAL_ROOT", f'"{catalogs["graph"]["canonicalRoot"]}"'),
        declaration("MOBILE_BASE", '"$CANONICAL_ROOT/mobile"'),
        declaration("HEALTH_CONNECT_BASE", '"$CANONICAL_ROOT/health-connect"'),
        "",
        declaration("MOBILE_OBSERVATION_PROFILE", profile_value(MOBILE_BASE, "grove-mobile-observation")),
        declaration(
            "MOBILE_EXCHANGE_BUNDLE_PROFILE", profile_value(MOBILE_BASE, "grove-mobile-exchange-bundle")
        ),
        declaration("MOBILE_APPLICATION_DEVICE_PROFILE", profile_value(MOBILE_BASE, "grove-application-device")),
        declaration("MOBILE_RECORDING_DEVICE_PROFILE", profile_value(MOBILE_BASE, "grove-recording-device")),
        declaration(
            "HEALTH_CONNECT_OBSERVATION_PROFILE",
            profile_value(HEALTH_CONNECT_BASE, "health-connect-observation"),
        ),
        declaration(
            "HEALTH_CONNECT_SPECIMEN_PROFILE",
            profile_value(HEALTH_CONNECT_BASE, "health-connect-specimen"),
        ),
        declaration(
            "HEALTH_CONNECT_PROVENANCE_PROFILE",
            profile_value(HEALTH_CONNECT_BASE, "health-connect-conversion-provenance"),
        ),
        "",
    ]

    for name, profile in shared:
        lines.append(declaration(name, profile_value(MOBILE_BASE, profile)))
    lines.append("")
    for name, profile in adapter_specific:
        lines.append(declaration(name, profile_value(HEALTH_CONNECT_BASE, profile)))
    lines.append("")

    lines.append("    /** Every dietary nutrient the adapter emits, keyed by its catalog measurement id. */")
    lines.append("    val mobileDietaryProfiles: Map<String, String> = mapOf(")
    for identifier, profile in dietary:
        # The canonical comes from the catalog, never from the id: deriving it would let a
        # renamed profile keep its old canonical with nothing failing.
        lines.append(f'        "{identifier}" to "$MOBILE_BASE/StructureDefinition/{profile}",')
    lines.append("    )")
    lines.append("")

    lines.append("    /** Profiles the shared Mobile package owns, which this adapter also claims. */")
    lines.append("    val sharedMeasurementProfiles: Set<String> = setOf(")
    for name, _ in shared:
        lines.append(f"        {name},")
    lines.append("    ) + mobileDietaryProfiles.values")
    lines.append("")
    lines.append("    /** Profiles only this adapter publishes. */")
    lines.append("    val adapterSpecificObservationProfiles: Set<String> = setOf(")
    for name, _ in adapter_specific:
        lines.append(f"        {name},")
    lines.append("    )")
    lines.append("")

    naming_systems = [
        ("HEALTH_CONNECT_RECORD_IDENTIFIER", "health-connect-record-id"),
        ("HEALTH_CONNECT_OUTPUT_IDENTIFIER", "health-connect-output-id"),
        ("HEALTH_CONNECT_SPECIMEN_IDENTIFIER", "health-connect-specimen-id"),
        ("ANDROID_PACKAGE_IDENTIFIER", "android-package-name"),
    ]
    for name, identifier in naming_systems:
        lines.append(declaration(name, system_value(HEALTH_CONNECT_BASE, "NamingSystem", identifier)))
    lines.append("")

    # One namespace serves every adapter, so the writer record identity is a Mobile canonical.
    lines.append(
        declaration("WRITER_RECORD_IDENTIFIER", system_value(MOBILE_BASE, "NamingSystem", "grove-writer-record-id"))
    )
    lines.append(
        declaration("WRITER_RECORD_VERSION", profile_value(MOBILE_BASE, "grove-writer-record-version"))
    )
    lines.append(
        declaration("RECORDING_METHOD_EXTENSION", profile_value(MOBILE_BASE, "grove-recording-method"))
    )
    for name, identifier in [
        ("HEALTH_CONNECT_SLEEP_TITLE", "health-connect-sleep-title"),
        ("HEALTH_CONNECT_EXERCISE_TITLE", "health-connect-exercise-title"),
        ("HEALTH_CONNECT_GLUCOSE_MEAL_CONTEXT", "health-connect-glucose-meal-context"),
        ("HEALTH_CONNECT_RECORD_TYPE_EXTENSION", "health-connect-record-type"),
    ]:
        lines.append(declaration(name, profile_value(HEALTH_CONNECT_BASE, identifier)))
    lines.append("")

    for name, identifier in mobile_code_systems(catalog_directory):
        lines.append(declaration(name, system_value(MOBILE_BASE, "CodeSystem", identifier)))
    for name, identifier in health_connect_code_systems(catalog_directory):
        lines.append(declaration(name, system_value(HEALTH_CONNECT_BASE, "CodeSystem", identifier)))
    lines.append("")

    for name, value, doc in EXTERNAL_SYSTEMS:
        lines.append(declaration(name, f'"{value}"', doc))
    lines.append("}")
    return HEADER + "\n".join(lines) + "\n"


def code_systems(guide_directory: Path) -> list[str]:
    """Every CodeSystem id a guide publishes, read from its FSH rather than restated here.

    Every failure here is loud. An empty result reads exactly like a guide with no code systems,
    and a contract missing its code systems still compiles.
    """
    fsh = guide_directory / "input" / "fsh"
    sources = sorted(fsh.glob("*.fsh"))
    if not sources:
        raise SystemExit(f"{fsh} holds no FSH; the contract cannot be projected from it")
    found: set[str] = set()
    for source in sources:
        declared: str | None = None
        identifier: str | None = None
        for line in source.read_text(encoding="utf-8").splitlines():
            header = re.match(r"^CodeSystem:\s+(\S+)", line)
            if header:
                if declared and identifier is None:
                    raise SystemExit(f"{source}: CodeSystem {declared} declares no Id")
                declared, identifier = header.group(1), None
                continue
            if re.match(r"^[A-Za-z]+:\s", line) and not line.startswith(("Id:", "Title:", "Description:")):
                if declared and identifier is None:
                    raise SystemExit(f"{source}: CodeSystem {declared} declares no Id")
                declared, identifier = None, None
                continue
            if declared and line.startswith("Id:"):
                identifier = line.split(":", 1)[1].strip()
                found.add(identifier)
        if declared and identifier is None:
            raise SystemExit(f"{source}: CodeSystem {declared} declares no Id")
    if not found:
        raise SystemExit(f"{fsh} declares no CodeSystem; the contract would silently lose them")
    return sorted(found)


def mobile_code_systems(catalog_directory: Path) -> list[tuple[str, str]]:
    guide = catalog_directory.parent / "mobile"
    return [
        # A code system keeps its package word: `grove-mobile-measurement` is not `grove-measurement`.
        (constant_name(identifier, prefix="GROVE", strip=r"^grove-"), identifier)
        for identifier in code_systems(guide)
    ]


def health_connect_code_systems(catalog_directory: Path) -> list[tuple[str, str]]:
    guide = catalog_directory.parent / "health-connect"
    return [(constant_name(identifier), identifier) for identifier in code_systems(guide)]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog-directory", type=Path, required=True)
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("health-fhir/src/main/kotlin/org/grovealliance/health/fhir/HealthConnectContract.kt"),
    )
    parser.add_argument("--check", action="store_true")
    arguments = parser.parse_args()
    generated = generate(arguments.catalog_directory)
    if arguments.check:
        actual = arguments.output.read_text(encoding="utf-8") if arguments.output.exists() else ""
        if actual != generated:
            print(
                f"error: {arguments.output} is not synchronized with the grove-fhir catalogs",
                file=sys.stderr,
            )
            return 1
        return 0
    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
