#
# This source file is part of the My Heart Counts Android open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Google Play Access Check

on:
  workflow_dispatch:

jobs:
  google_play_access:
    name: Google Play Access
    uses: SchmiedmayerLab/.github/.github/workflows/android-google-play-access.yml@v0.5
    permissions:
      contents: read
    secrets: inherit
