#
# This source file is part of the My Heart Counts Android open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Monthly Markdown Link Check

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  markdown_links:
    name: Markdown Links
    uses: SchmiedmayerLab/.github/.github/workflows/markdown-links.yml@v0.5
    permissions:
      contents: read
      pull-requests: read
