#
# This source file is part of the Grove open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Pull Request Checks

on:
  pull_request:
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  android:
    name: Android
    uses: SchmiedmayerLab/.github/.github/workflows/android.yml@v0.5
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write
    secrets: inherit
