#
# This source file is part of the My Heart Counts Android open-source project
#
# SPDX-FileCopyrightText: 2026 Stanford University and the project authors (see CONTRIBUTORS.md)
#
# SPDX-License-Identifier: MIT
#

name: Google Play Release

on:
  release:
    types:
      - published

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  format_release_notes:
    name: Format Release Notes
    uses: SchmiedmayerLab/.github/.github/workflows/format-release-notes.yml@v0.5
    permissions:
      contents: read
    with:
      release-tag: ${{ github.event.release.tag_name }}
      repository: ${{ github.repository }}

  deployment:
    name: Production Deployment
    uses: ./.github/workflows/deployment.yml
    needs:
      - format_release_notes
    permissions:
      actions: read
      contents: write
      packages: read
      security-events: write
    secrets: inherit
    with:
      environment: production
      version: ${{ github.event.release.tag_name }}
      releasenotes: ${{ needs.format_release_notes.outputs.releasenotes }}
